/**
 * ResolveConsentState handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { resolveConsentState } from "@loadline/api-server/domains/scoring/handlers";
import type { ScoringDDDDependencies } from "@loadline/api-server/domains/scoring";
import { createConsent as createConsentEntity } from "@loadline/factories/scoring";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { SCORING_USE_CASES } from "../__factories__/use-cases.js";

describe("ResolveConsentState", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ScoringDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ScoringDDDDependencies>(
      SCORING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createConsentEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeResolveConsentState, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { riskSubjectId: entity.id };

    await resolveConsentState(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeResolveConsentState.execute).toHaveBeenCalledWith(expect.objectContaining({ riskSubjectId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { riskSubjectId: nonExistentId };
    
    vi.spyOn(mockDeps.executeResolveConsentState, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      resolveConsentState(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
