/**
 * ExecuteApplyCommercialCalibration - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteApplyCommercialCalibration Use Case
 *
 * DDD: Application use case for get Calibration.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ApplyCommercialCalibrationInput, ApplyCommercialCalibrationOutput } from "../dto/calibration.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { CalibrationRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteApplyCommercialCalibration {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly calibration: CalibrationRepository
  ) {}

  async execute(input: ApplyCommercialCalibrationInput): Promise<ApplyCommercialCalibrationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmpId();

    // All field names extracted from OpenAPI spec: approvedBy, calibratedPrice, narrative, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).compositionId) {
      throw new ValidationError("compositionId is required");
    }
    const compositionId = (input as any).compositionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.calibration.applyCommercialCalibration({ compositionId: compositionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${compositionId}`);
    }

    return entity as ApplyCommercialCalibrationOutput;
  }
}
