/**
 * CessionExperienceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CessionExperienceRepository Port
 *
 * DDD: Application port for cessionexperiencerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCessionExperienceInput, GetCessionExperienceOutput } from "../dto/cession-experience.dto.js";
export interface CessionExperienceRepository {
  getCessionExperience(input: GetCessionExperienceInput): Promise<GetCessionExperienceOutput>;
}

export type { GetCessionExperienceInput, GetCessionExperienceOutput } from "../dto/cession-experience.dto.js";
