/**
 * ReviewRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReviewRepository Port
 *
 * DDD: Application port for reviewrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RequestHumanReviewInput, RequestHumanReviewOutput } from "../dto/review.dto.js";
export interface ReviewRepository {
  requestHumanReview(input: RequestHumanReviewInput): Promise<RequestHumanReviewOutput>;
}

export type { RequestHumanReviewInput, RequestHumanReviewOutput } from "../dto/review.dto.js";
