/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@loadline/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildClaimsDomainModule,
  buildCompositionDomainModule,
  buildEngagementDomainModule,
  buildExperienceDomainModule,
  buildIdentityDomainModule,
  buildPermittingDomainModule,
  buildReinsuranceDomainModule,
  buildScoringDomainModule,
} from "../domains/index.js";
import type {
  ClaimsDomainModule,
  CompositionDomainModule,
  EngagementDomainModule,
  ExperienceDomainModule,
  IdentityDomainModule,
  PermittingDomainModule,
  ReinsuranceDomainModule,
  ScoringDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private claimsModule: ClaimsDomainModule | null = null;
  private compositionModule: CompositionDomainModule | null = null;
  private engagementModule: EngagementDomainModule | null = null;
  private experienceModule: ExperienceDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private permittingModule: PermittingDomainModule | null = null;
  private reinsuranceModule: ReinsuranceDomainModule | null = null;
  private scoringModule: ScoringDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get claims domain module
   */
  getClaimsDependencies(): ClaimsDomainModule {
    if (!this.claimsModule) {
      this.claimsModule = buildClaimsDomainModule(this.dynamoClient);
    }
    return this.claimsModule;
  }

  /**
   * Get composition domain module
   */
  getCompositionDependencies(): CompositionDomainModule {
    if (!this.compositionModule) {
      this.compositionModule = buildCompositionDomainModule(this.dynamoClient);
    }
    return this.compositionModule;
  }

  /**
   * Get engagement domain module
   */
  getEngagementDependencies(): EngagementDomainModule {
    if (!this.engagementModule) {
      this.engagementModule = buildEngagementDomainModule(this.dynamoClient);
    }
    return this.engagementModule;
  }

  /**
   * Get experience domain module
   */
  getExperienceDependencies(): ExperienceDomainModule {
    if (!this.experienceModule) {
      this.experienceModule = buildExperienceDomainModule(this.dynamoClient);
    }
    return this.experienceModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get permitting domain module
   */
  getPermittingDependencies(): PermittingDomainModule {
    if (!this.permittingModule) {
      this.permittingModule = buildPermittingDomainModule(this.dynamoClient);
    }
    return this.permittingModule;
  }

  /**
   * Get reinsurance domain module
   */
  getReinsuranceDependencies(): ReinsuranceDomainModule {
    if (!this.reinsuranceModule) {
      this.reinsuranceModule = buildReinsuranceDomainModule(this.dynamoClient);
    }
    return this.reinsuranceModule;
  }

  /**
   * Get scoring domain module
   */
  getScoringDependencies(): ScoringDomainModule {
    if (!this.scoringModule) {
      this.scoringModule = buildScoringDomainModule(this.dynamoClient);
    }
    return this.scoringModule;
  }

  clearClaimsDependencies(): void { this.claimsModule = null; }
  clearCompositionDependencies(): void { this.compositionModule = null; }
  clearEngagementDependencies(): void { this.engagementModule = null; }
  clearExperienceDependencies(): void { this.experienceModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearPermittingDependencies(): void { this.permittingModule = null; }
  clearReinsuranceDependencies(): void { this.reinsuranceModule = null; }
  clearScoringDependencies(): void { this.scoringModule = null; }

  getClaimsDependenciesForRequest(): ClaimsDomainModule {
    return this.getClaimsDependencies();
  }

  getCompositionDependenciesForRequest(): CompositionDomainModule {
    return this.getCompositionDependencies();
  }

  getEngagementDependenciesForRequest(): EngagementDomainModule {
    return this.getEngagementDependencies();
  }

  getExperienceDependenciesForRequest(): ExperienceDomainModule {
    return this.getExperienceDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getPermittingDependenciesForRequest(): PermittingDomainModule {
    return this.getPermittingDependencies();
  }

  getReinsuranceDependenciesForRequest(): ReinsuranceDomainModule {
    return this.getReinsuranceDependencies();
  }

  getScoringDependenciesForRequest(): ScoringDomainModule {
    return this.getScoringDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.claimsModule = null;
    this.compositionModule = null;
    this.engagementModule = null;
    this.experienceModule = null;
    this.identityModule = null;
    this.permittingModule = null;
    this.reinsuranceModule = null;
    this.scoringModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
