/**
 * Routes for Offer
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { issuePriceOffer } from "../handlers/offer.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function offerRoutes(fastify: FastifyInstance) {
  // POST /v1/compositions/{compositionId}/offer (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/compositions/:compositionId/offer",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { compositionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCompositionDependenciesForRequest();
        await issuePriceOffer(request, reply, deps);
      });
    }
  );


}
