/**
 * ExecuteRaiseFraudReferral - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRaiseFraudReferral Use Case
 *
 * DDD: Application use case for get FraudReferral.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RaiseFraudReferralInput, RaiseFraudReferralOutput } from "../dto/fraud-referral.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { FraudReferralRepository } from "../ports/index.js";
import { NotFoundError } from "../errors/index.js";

export class ExecuteRaiseFraudReferral {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fraudReferral: FraudReferralRepository
  ) {}

  async execute(input: RaiseFraudReferralInput): Promise<RaiseFraudReferralOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.clmId();

    // All field names extracted from OpenAPI spec: anomalyKind, claimReference, indicators, score
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.fraudReferral.raiseFraudReferral({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as RaiseFraudReferralOutput;
  }
}
