/**
 * CalibrationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CalibrationRepository Port
 *
 * DDD: Application port for calibrationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ApplyCommercialCalibrationInput, ApplyCommercialCalibrationOutput } from "../dto/calibration.dto.js";
export interface CalibrationRepository {
  applyCommercialCalibration(input: ApplyCommercialCalibrationInput): Promise<ApplyCommercialCalibrationOutput>;
}

export type { ApplyCommercialCalibrationInput, ApplyCommercialCalibrationOutput } from "../dto/calibration.dto.js";
