/**
 * CompositionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompositionRepository Port
 *
 * DDD: Application port for compositionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ComposePremiumInput, ComposePremiumOutput } from "../dto/composition.dto.js";
export interface CompositionRepository {
  composePremium(input: ComposePremiumInput): Promise<ComposePremiumOutput>;
}

export type { ComposePremiumInput, ComposePremiumOutput } from "../dto/composition.dto.js";
