/**
 * VariationEnvelopeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VariationEnvelopeRepository Port
 *
 * DDD: Application port for variationenveloperepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListVariationEnvelopesInput, ListVariationEnvelopesOutput, SetVariationEnvelopeInput, SetVariationEnvelopeOutput } from "../dto/variation-envelope.dto.js";
export interface VariationEnvelopeRepository {
  listVariationEnvelopes(input: ListVariationEnvelopesInput): Promise<ListVariationEnvelopesOutput>;
  setVariationEnvelope(input: SetVariationEnvelopeInput): Promise<SetVariationEnvelopeOutput>;
}

export type { ListVariationEnvelopesInput, ListVariationEnvelopesOutput, SetVariationEnvelopeInput, SetVariationEnvelopeOutput } from "../dto/variation-envelope.dto.js";
