/**
 * ValidationQueue Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ValidationQueueEntity } from "@loadline/core/permitting/models/index.js";
import { permittingSchemas } from "@loadline/core/permitting";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prm";

export function createValidationQueue(overrides: Partial<ValidationQueueEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    ...overrides,
  };

  return permittingSchemas.ValidationQueue.parse(raw);
}

export function validationQueueBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createValidationQueue(overrides));
}
