/**
 * CohortRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CohortRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CohortRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CohortRepository,
} from "@loadline/services/experience";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CohortRepositoryDdb } from "./cohort-repository.ddb.js";

/**
 * CohortRepositoryAdapter
 *
 * Implements CohortRepository port for infrastructure layer.
 */
export class CohortRepositoryAdapter implements CohortRepository {
  private readonly ddb: CohortRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CohortRepositoryDdb(this.dynamoClient);
  }

  async listCohortDefinitions(input: Parameters<CohortRepository['listCohortDefinitions']>[0]): Promise<Awaited<ReturnType<CohortRepository['listCohortDefinitions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCohortDefinitions(input);
  }

  async defineCohort(input: Parameters<CohortRepository['defineCohort']>[0]): Promise<Awaited<ReturnType<CohortRepository['defineCohort']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.defineCohort(input);
  }
}
