/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./cohort-repository.ddb.js";
export * from "./observation-repository.ddb.js";
export * from "./savings-credit-repository.ddb.js";
export * from "./cohort-repository.adapter.js";
export * from "./observation-repository.adapter.js";
export * from "./savings-credit-repository.adapter.js";
