/**
 * FactorPermit Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { FactorPermitEntity } from "@loadline/core/permitting/models/index.js";
import { permittingSchemas } from "@loadline/core/permitting";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prm";

export function createFactorPermit(overrides: Partial<FactorPermitEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    factor: overrides.factor ?? faker.lorem.word(),
    jurisdiction: overrides.jurisdiction ?? faker.internet.url(),
    position: overrides.position ?? "permitted",
    ...overrides,
  };

  return permittingSchemas.FactorPermit.parse(raw);
}

export function factorPermitBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFactorPermit(overrides));
}
