/**
 * VariationEnvelope DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VariationEnvelope DTOs
 *
 * DDD: Application DTOs for VariationEnvelope use cases.
 */

import type { ListVariationEnvelopesParams, SetVariationEnvelopeRequestInput } from "@loadline/core/composition/types";

export type ListVariationEnvelopesInput = ListVariationEnvelopesParams;

export type SetVariationEnvelopeInput = SetVariationEnvelopeRequestInput;

export type ListVariationEnvelopesOutput = {};

export type SetVariationEnvelopeOutput = {};
