/**
 * Repository interface for CessionExperience
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CessionExperienceEntity
} from "../models/cession-experience.entity.js";
import type {
  GetCessionExperienceParams
} from "../types/index.js";
/**
 * CessionExperienceRepository Interface
 */
export interface CessionExperienceRepository extends ReadRepository<CessionExperienceEntity, string, GetCessionExperienceParams> {

}
