/**
 * Repository interface for Review
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ReviewEntity
} from "../models/review.entity.js";
import type {
  ReviewDecision
} from "../types/index.js";
/**
 * ReviewRepository Interface
 */
export interface ReviewRepository extends CreateReadRepository<ReviewEntity, ReviewDecision, string, Record<string, never>> {

}
