/**
 * ListPermittingModel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListRiskModelsParams } from "@loadline/core/permitting";

export function createListPermittingModelRequest(overrides: Partial<ListRiskModelsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
