/**
 * FraudReferral Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/claims.openapi.types.js";
import { schemas } from "../schemas/claims.schemas.js";

/**
 * Entity: FraudReferralEntity
 * Description: Represents the FraudReferral domain model.
 * Source: schemas.FraudReferral
 * Type: Persisted Entity (x-dynamodb)
 */
export const FraudReferralEntitySchema = schemas.FraudReferral;
export type FraudReferralEntity = components["schemas"]["FraudReferral"];
