services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.2
    container_name: ddd-dynamodb-local
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
    working_dir: /home/dynamodblocal
