/**
 * Touchpoint DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Touchpoint DTOs
 *
 * DDD: Application DTOs for Touchpoint use cases.
 */

import type { RecordTouchpointEventRequestInput } from "@loadline/core/engagement/types";

export type RecordTouchpointEventInput = RecordTouchpointEventRequestInput;

export type RecordTouchpointEventOutput = {};
