/**
 * ProgrammeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProgrammeRepository Port
 *
 * DDD: Application port for programmerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateEngagementProgrammeInput, CreateEngagementProgrammeOutput, ListEngagementProgrammesInput, ListEngagementProgrammesOutput } from "../dto/programme.dto.js";
export interface ProgrammeRepository {
  listEngagementProgrammes(input: ListEngagementProgrammesInput): Promise<ListEngagementProgrammesOutput>;
  createEngagementProgramme(input: CreateEngagementProgrammeInput): Promise<CreateEngagementProgrammeOutput>;
}

export type { CreateEngagementProgrammeInput, CreateEngagementProgrammeOutput, ListEngagementProgrammesInput, ListEngagementProgrammesOutput } from "../dto/programme.dto.js";
