/**
 * TouchpointRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TouchpointRepository Port
 *
 * DDD: Application port for touchpointrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordTouchpointEventInput, RecordTouchpointEventOutput } from "../dto/touchpoint.dto.js";
export interface TouchpointRepository {
  recordTouchpointEvent(input: RecordTouchpointEventInput): Promise<RecordTouchpointEventOutput>;
}

export type { RecordTouchpointEventInput, RecordTouchpointEventOutput } from "../dto/touchpoint.dto.js";
