/**
 * CreateEngagementProgramme handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createEngagementProgramme } from "@loadline/api-server/domains/engagement/handlers";
import type { EngagementDDDDependencies } from "@loadline/api-server/domains/engagement";
import { createProgramme as createProgrammeEntity } from "@loadline/factories/engagement";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { ENGAGEMENT_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateEngagementProgramme", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EngagementDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EngagementDDDDependencies>(
      ENGAGEMENT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createProgrammeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateEngagementProgramme, "execute").mockResolvedValue(useCaseResult);

    await createEngagementProgramme(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateEngagementProgramme.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
