/**
 * ListEngagementProgrammes handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listEngagementProgrammes } from "@loadline/api-server/domains/engagement/handlers";
import type { EngagementDDDDependencies } from "@loadline/api-server/domains/engagement";
import { createProgramme as createProgrammeEntity } from "@loadline/factories/engagement";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { ENGAGEMENT_USE_CASES } from "../__factories__/use-cases.js";

describe("ListEngagementProgrammes", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EngagementDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EngagementDDDDependencies>(
      ENGAGEMENT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createProgrammeEntity({ orgId }),
      createProgrammeEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListEngagementProgrammes, "execute").mockResolvedValue(useCaseResult);

    await listEngagementProgrammes(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListEngagementProgrammes.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
