/**
 * Repository interface for VariationEnvelope
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  VariationEnvelopeEntity
} from "../models/variation-envelope.entity.js";
import type {
  ListVariationEnvelopesParams,
  SetVariationEnvelopeRequestInput
} from "../types/index.js";
/**
 * VariationEnvelopeRepository Interface
 */
export interface VariationEnvelopeRepository extends UpdateReadRepository<VariationEnvelopeEntity, SetVariationEnvelopeRequestInput, string, ListVariationEnvelopesParams> {

}
