/**
 * FactorPermit Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/permitting.openapi.types.js";
import { schemas } from "../schemas/permitting.schemas.js";

/**
 * Entity: FactorPermitEntity
 * Description: Represents the FactorPermit domain model.
 * Source: schemas.FactorPermit
 * Type: Persisted Entity (x-dynamodb)
 */
export const FactorPermitEntitySchema = schemas.FactorPermit;
export type FactorPermitEntity = components["schemas"]["FactorPermit"];
