/**
 * PermittingModel Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/permitting.openapi.types.js";
import { schemas } from "../schemas/permitting.schemas.js";

/**
 * Entity: PermittingModelEntity
 * Description: Represents the PermittingModel domain model.
 * Source: schemas.RiskModel
 * Type: Persisted Entity (x-dynamodb)
 */
export const PermittingModelEntitySchema = schemas.RiskModel;
export type PermittingModelEntity = components["schemas"]["RiskModel"];
