/**
 * ValidationQueue Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/permitting.openapi.types.js";
import { schemas } from "../schemas/permitting.schemas.js";

/**
 * Entity: ValidationQueueEntity
 * Description: Represents the ValidationQueue domain model.
 * Source: schemas.ValidationQueue
 * Type: Domain Entity (API)
 */
export const ValidationQueueEntitySchema = schemas.ValidationQueue;
export type ValidationQueueEntity = components["schemas"]["ValidationQueue"];
