/**
 * ScoreRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScoreRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ScoreRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ScoreRepository,
} from "@loadline/services/scoring";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ScoreRepositoryDdb } from "./score-repository.ddb.js";

/**
 * ScoreRepositoryAdapter
 *
 * Implements ScoreRepository port for infrastructure layer.
 */
export class ScoreRepositoryAdapter implements ScoreRepository {
  private readonly ddb: ScoreRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ScoreRepositoryDdb(this.dynamoClient);
  }

  async scoreRiskSubject(input: Parameters<ScoreRepository['scoreRiskSubject']>[0]): Promise<Awaited<ReturnType<ScoreRepository['scoreRiskSubject']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.scoreRiskSubject(input);
  }
}
