/**
 * ConsentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRepository Port
 *
 * DDD: Application port for consentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordConsentChangeInput, RecordConsentChangeOutput, ResolveConsentStateInput, ResolveConsentStateOutput } from "../dto/consent.dto.js";
export interface ConsentRepository {
  resolveConsentState(input: ResolveConsentStateInput): Promise<ResolveConsentStateOutput>;
  recordConsentChange(input: RecordConsentChangeInput): Promise<RecordConsentChangeOutput>;
}

export type { RecordConsentChangeInput, RecordConsentChangeOutput, ResolveConsentStateInput, ResolveConsentStateOutput } from "../dto/consent.dto.js";
