/**
 * ExplanationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExplanationRepository Port
 *
 * DDD: Application port for explanationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetScoreExplanationInput, GetScoreExplanationOutput } from "../dto/explanation.dto.js";
export interface ExplanationRepository {
  getScoreExplanation(input: GetScoreExplanationInput): Promise<GetScoreExplanationOutput>;
}

export type { GetScoreExplanationInput, GetScoreExplanationOutput } from "../dto/explanation.dto.js";
