/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Claims Domain Use Cases
 * 
 * List of all use case names for the claims domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CLAIMS_USE_CASES = [
  "executeGetExpenseMeasurement",
  "executeRaiseFraudReferral",
  "executeSettleClaimAutomatically"
] as const;
