/**
 * Programme Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/engagement.openapi.types.js";
import { schemas } from "../schemas/engagement.schemas.js";

/**
 * Entity: ProgrammeEntity
 * Description: Represents the Programme domain model.
 * Source: schemas.EngagementProgramme
 * Type: Persisted Entity (x-dynamodb)
 */
export const ProgrammeEntitySchema = schemas.EngagementProgramme;
export type ProgrammeEntity = components["schemas"]["EngagementProgramme"];
