/**
 * Touchpoint Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/engagement.openapi.types.js";
import { schemas } from "../schemas/engagement.schemas.js";

/**
 * Entity: TouchpointEntity
 * Description: Represents the Touchpoint domain model.
 * Source: schemas.TouchpointEvent
 * Type: Persisted Entity (x-dynamodb)
 */
export const TouchpointEntitySchema = schemas.TouchpointEvent;
export type TouchpointEntity = components["schemas"]["TouchpointEvent"];
