/**
 * Cohort DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cohort DTOs
 *
 * DDD: Application DTOs for Cohort use cases.
 */

import type { DefineCohortRequestInput, ListCohortDefinitionsParams } from "@loadline/core/experience/types";

export type ListCohortDefinitionsInput = ListCohortDefinitionsParams;

export type DefineCohortInput = DefineCohortRequestInput;

export type ListCohortDefinitionsOutput = {};

export type DefineCohortOutput = {};
