/**
 * PermittingModelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PermittingModelRepository Port
 *
 * DDD: Application port for permittingmodelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListRiskModelsInput, ListRiskModelsOutput, SubmitRiskModelInput, SubmitRiskModelOutput } from "../dto/permitting-model.dto.js";
export interface PermittingModelRepository {
  listRiskModels(input: ListRiskModelsInput): Promise<ListRiskModelsOutput>;
  submitRiskModel(input: SubmitRiskModelInput): Promise<SubmitRiskModelOutput>;
}

export type { ListRiskModelsInput, ListRiskModelsOutput, SubmitRiskModelInput, SubmitRiskModelOutput } from "../dto/permitting-model.dto.js";
