/**
 * Handlers for Composition
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CompositionDomainModule } from "../dependencies/composition-ddd.dependencies.js";
import type { ComposePremiumInput } from "@loadline/services/composition";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/compositions
 * Operation: composePremium
 */
export async function composePremium(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CompositionDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ComposePremiumInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.compositions.get.execute(input);
  return reply.code(201).send(result);
}


