/**
 * Handlers for Consent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScoringDomainModule } from "../dependencies/scoring-ddd.dependencies.js";
import type { RecordConsentChangeInput, ResolveConsentStateInput } from "@loadline/services/scoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/risk-subjects/{riskSubjectId}/consent
 * Operation: resolveConsentState
 */
export async function resolveConsentState(
  request: FastifyRequest<{ Params: { riskSubjectId: string }; Querystring: { purpose?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ResolveConsentStateInput = {
    riskSubjectId: request.params.riskSubjectId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.consents.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/risk-subjects/{riskSubjectId}/consent
 * Operation: recordConsentChange
 */
export async function recordConsentChange(
  request: FastifyRequest<{ Params: { riskSubjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordConsentChangeInput = {
    riskSubjectId: request.params.riskSubjectId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.consents.get.execute(input);
  return reply.code(201).send(result);
}


