/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./cession-experience-repository.ddb.js";
export * from "./review-repository.ddb.js";
export * from "./cession-experience-repository.adapter.js";
export * from "./review-repository.adapter.js";
