/**
 * ApiKeyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApiKeyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApiKeyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ApiKeyRepository,
} from "@loadline/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ApiKeyRepositoryDdb } from "./api-key-repository.ddb.js";

/**
 * ApiKeyRepositoryAdapter
 *
 * Implements ApiKeyRepository port for infrastructure layer.
 */
export class ApiKeyRepositoryAdapter implements ApiKeyRepository {
  private readonly ddb: ApiKeyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ApiKeyRepositoryDdb(this.dynamoClient);
  }

  async listTenantApiKeys(input: Parameters<ApiKeyRepository['listTenantApiKeys']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['listTenantApiKeys']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTenantApiKeys(input);
  }

  async createTenantApiKey(input: Parameters<ApiKeyRepository['createTenantApiKey']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['createTenantApiKey']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createTenantApiKey(input);
  }

  async getTenantApiKey(input: Parameters<ApiKeyRepository['getTenantApiKey']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['getTenantApiKey']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTenantApiKey(input);
  }

  async revokeTenantApiKey(input: Parameters<ApiKeyRepository['revokeTenantApiKey']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['revokeTenantApiKey']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.revokeTenantApiKey(input);
  }
}
