/**
 * LoginRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LoginRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LoginRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LoginRepository,
} from "@loadline/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LoginRepositoryDdb } from "./login-repository.ddb.js";

/**
 * LoginRepositoryAdapter
 *
 * Implements LoginRepository port for infrastructure layer.
 */
export class LoginRepositoryAdapter implements LoginRepository {
  private readonly ddb: LoginRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LoginRepositoryDdb(this.dynamoClient);
  }

  async operatorLogin(input: Parameters<LoginRepository['operatorLogin']>[0]): Promise<Awaited<ReturnType<LoginRepository['operatorLogin']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.operatorLogin(input);
  }
}
