/**
 * LogoutRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LogoutRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LogoutRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LogoutRepository,
} from "@loadline/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LogoutRepositoryDdb } from "./logout-repository.ddb.js";

/**
 * LogoutRepositoryAdapter
 *
 * Implements LogoutRepository port for infrastructure layer.
 */
export class LogoutRepositoryAdapter implements LogoutRepository {
  private readonly ddb: LogoutRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LogoutRepositoryDdb(this.dynamoClient);
  }

  async operatorLogout(input: Parameters<LogoutRepository['operatorLogout']>[0]): Promise<Awaited<ReturnType<LogoutRepository['operatorLogout']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.operatorLogout(input);
  }
}
