/**
 * RefreshRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RefreshRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RefreshRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RefreshRepository,
} from "@loadline/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RefreshRepositoryDdb } from "./refresh-repository.ddb.js";

/**
 * RefreshRepositoryAdapter
 *
 * Implements RefreshRepository port for infrastructure layer.
 */
export class RefreshRepositoryAdapter implements RefreshRepository {
  private readonly ddb: RefreshRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RefreshRepositoryDdb(this.dynamoClient);
  }

  async operatorRefresh(input: Parameters<RefreshRepository['operatorRefresh']>[0]): Promise<Awaited<ReturnType<RefreshRepository['operatorRefresh']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.operatorRefresh(input);
  }
}
