/**
 * Reinsurance Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const requestHumanReview_Body = z
  .object({
    requestedBy: z.enum([
      'applicant',
      'policyholder',
      'claimant',
      'distributor',
      'underwriter',
    ]),
    grounds: z.string(),
  })
  .passthrough();

export const schemas: any = {
  requestHumanReview_Body,
};

const endpoints = makeApi([
  {
    method: 'post',
    path: '/v1/decisions/:decisionId/review',
    alias: 'requestHumanReview',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: requestHumanReview_Body,
      },
      {
        name: 'decisionId',
        type: 'Path',
        schema: z.string(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            decisionId: z.string(),
            decisionKind: z
              .enum([
                'declinature',
                'exclusion',
                'loading',
                'claims_decision',
                'price_refusal',
              ])
              .optional(),
            requestedBy: z.string().optional(),
            grounds: z.string().optional(),
            status: z.enum([
              'open',
              'upheld',
              'overturned',
              'partially_overturned',
            ]),
            reviewerId: z.string().optional(),
            explanationProvided: z.boolean().optional(),
            resolvedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
  },
  {
    method: 'get',
    path: '/v1/reinsurance/cession-experience',
    alias: 'getCessionExperience',
    requestFormat: 'json',
    parameters: [
      {
        name: 'treatyId',
        type: 'Query',
        schema: z.string(),
      },
      {
        name: 'cohortId',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'period',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            treatyId: z.string(),
            cohortId: z.string(),
            period: z.string(),
            cededExposureYears: z.number(),
            cededClaims: z
              .object({ amount: z.number(), currency: z.string() })
              .passthrough(),
            pricingBasisExpected: z
              .object({ amount: z.number(), currency: z.string() })
              .passthrough(),
            actualToExpected: z.number(),
            assumptionsHolding: z.boolean(),
            sharedWithCounterparty: z.boolean(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
