/**
 * ListVariationEnvelopes handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listVariationEnvelopes } from "@loadline/api-server/domains/composition/handlers";
import type { CompositionDDDDependencies } from "@loadline/api-server/domains/composition";
import { createVariationEnvelope as createVariationEnvelopeEntity } from "@loadline/factories/composition";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { COMPOSITION_USE_CASES } from "../__factories__/use-cases.js";

describe("ListVariationEnvelopes", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CompositionDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CompositionDDDDependencies>(
      COMPOSITION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createVariationEnvelopeEntity({ orgId }),
      createVariationEnvelopeEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListVariationEnvelopes, "execute").mockResolvedValue(useCaseResult);

    await listVariationEnvelopes(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListVariationEnvelopes.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
