/**
 * ExecuteListTenantUsers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTenantUsers Use Case
 *
 * DDD: Application use case for list User.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTenantUsersInput, ListTenantUsersOutput } from "../dto/user.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { UserRepository } from "../ports/index.js";

export class ExecuteListTenantUsers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly user: UserRepository
  ) {}

  async execute(input: ListTenantUsersInput): Promise<ListTenantUsersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.idnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.user.listTenantUsers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTenantUsersOutput;
  }
}
