/**
 * ExecuteGetOperatorMe - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetOperatorMe Use Case
 *
 * DDD: Application use case for get Me.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetOperatorMeInput, GetOperatorMeOutput } from "../dto/me.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { MeRepository } from "../ports/index.js";
import { NotFoundError } from "../errors/index.js";

export class ExecuteGetOperatorMe {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly me: MeRepository
  ) {}

  async execute(input: GetOperatorMeInput): Promise<GetOperatorMeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.idnId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.me.getOperatorMe({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetOperatorMeOutput;
  }
}
