/**
 * ExecuteUpdateTenantUser - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateTenantUser Use Case
 *
 * DDD: Application use case for update User.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateTenantUserInput, UpdateTenantUserOutput } from "../dto/user.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { UserRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanUpdate } from "../policies/can-update.policy.js";
export class ExecuteUpdateTenantUser {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly user: UserRepository
  ) {}

  async execute(input: UpdateTenantUserInput): Promise<UpdateTenantUserOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.idnId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).userId) {
      throw new ValidationError("userId is required");
    }
    const userId = (input as any).userId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.user.updateTenantUser({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateTenantUserOutput;
  }
}
