/**
 * ExecuteListTenantApiKeys - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTenantApiKeys Use Case
 *
 * DDD: Application use case for list ApiKey.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTenantApiKeysInput, ListTenantApiKeysOutput } from "../dto/api-key.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { ApiKeyRepository } from "../ports/index.js";

export class ExecuteListTenantApiKeys {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly apiKey: ApiKeyRepository
  ) {}

  async execute(input: ListTenantApiKeysInput): Promise<ListTenantApiKeysOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.idnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.apiKey.listTenantApiKeys({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTenantApiKeysOutput;
  }
}
