/**
 * ExecuteCreateTenantApiKey - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateTenantApiKey Use Case
 *
 * DDD: Application use case for create ApiKey.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateTenantApiKeyInput, CreateTenantApiKeyOutput } from "../dto/api-key.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { ApiKeyRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanCreate } from "../policies/can-create.policy.js";
export class ExecuteCreateTenantApiKey {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly apiKey: ApiKeyRepository
  ) {}

  async execute(input: CreateTenantApiKeyInput): Promise<CreateTenantApiKeyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.idnId();

    // All field names extracted from OpenAPI spec: expiresAt, name, scopes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (identity domain)
    const entityId = this.idGenerator.idnId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.apiKey.createTenantApiKey({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateTenantApiKeyOutput;
  }
}
