/**
 * ExecuteGetTenantApiKey - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetTenantApiKey Use Case
 *
 * DDD: Application use case for get ApiKey.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetTenantApiKeyInput, GetTenantApiKeyOutput } from "../dto/api-key.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { ApiKeyRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteGetTenantApiKey {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly apiKey: ApiKeyRepository
  ) {}

  async execute(input: GetTenantApiKeyInput): Promise<GetTenantApiKeyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.idnId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).keyId) {
      throw new ValidationError("keyId is required");
    }
    const keyId = (input as any).keyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.apiKey.getTenantApiKey({ keyId: keyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${keyId}`);
    }

    return entity as GetTenantApiKeyOutput;
  }
}
