/**
 * Handlers for Validation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PermittingDomainModule } from "../dependencies/permitting-ddd.dependencies.js";
import type { ValidateRiskModelInput } from "@loadline/services/permitting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/permitting/models/{modelId}/validation
 * Operation: validateRiskModel
 */
export async function validateRiskModel(
  request: FastifyRequest<{ Params: { modelId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PermittingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ValidateRiskModelInput = {
    modelId: request.params.modelId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.validations.get.execute(input);
  return reply.code(200).send(result);
}


