/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/permitting/factor-permits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Factor Permits */
        get: operations["listFactorPermits"];
        put?: never;
        /** Record Factor Permit */
        post: operations["recordFactorPermit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permitting/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Risk Models */
        get: operations["listRiskModels"];
        put?: never;
        /** Submit Risk Model */
        post: operations["submitRiskModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permitting/models/{modelId}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Risk Model */
        post: operations["validateRiskModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permitting/validation-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Validation Queue */
        get: operations["getValidationQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DataCategory: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        FactorPermit: {
            id: string;
            /** @example residential_postcode_mortality_index */
            factor: string;
            /** @enum {string} */
            dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
            jurisdiction: string;
            /** @enum {string} */
            position: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
            /** @description Whether the factor proxies a protected characteristic */
            proxyRiskAssessment?: string;
            /** @description Statutory or moratorium position for genetic and similar data */
            restrictedHealthDataBasis?: string;
            explainableToApplicant?: boolean;
            conditions?: string[];
            officerId?: string;
            /** Format: date-time */
            reviewedAt?: string;
            /** Format: date */
            nextReviewDue?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ListEnvelopeFactorPermit: {
            data: {
                items: {
                    id: string;
                    /** @example residential_postcode_mortality_index */
                    factor: string;
                    /** @enum {string} */
                    dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
                    jurisdiction: string;
                    /** @enum {string} */
                    position: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
                    /** @description Whether the factor proxies a protected characteristic */
                    proxyRiskAssessment?: string;
                    /** @description Statutory or moratorium position for genetic and similar data */
                    restrictedHealthDataBasis?: string;
                    explainableToApplicant?: boolean;
                    conditions?: string[];
                    officerId?: string;
                    /** Format: date-time */
                    reviewedAt?: string;
                    /** Format: date */
                    nextReviewDue?: string;
                    /** Format: date-time */
                    createdAt?: string;
                    /** Format: date-time */
                    updatedAt?: string;
                }[];
                nextCursor?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        FactorPermitCreate: {
            factor: string;
            /** @enum {string} */
            dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
            jurisdiction: string;
            /** @enum {string} */
            position: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
            proxyRiskAssessment?: string;
            restrictedHealthDataBasis?: string;
            explainableToApplicant?: boolean;
            conditions?: string[];
            officerId: string;
        };
        DataEnvelopeFactorPermit: {
            data: {
                id: string;
                /** @example residential_postcode_mortality_index */
                factor: string;
                /** @enum {string} */
                dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
                jurisdiction: string;
                /** @enum {string} */
                position: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
                /** @description Whether the factor proxies a protected characteristic */
                proxyRiskAssessment?: string;
                /** @description Statutory or moratorium position for genetic and similar data */
                restrictedHealthDataBasis?: string;
                explainableToApplicant?: boolean;
                conditions?: string[];
                officerId?: string;
                /** Format: date-time */
                reviewedAt?: string;
                /** Format: date */
                nextReviewDue?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /**
         * @description The term of the price a model or lever acts on
         * @enum {string}
         */
        PremiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
        RiskModel: {
            id: string;
            name: string;
            /**
             * @description The term of the price a model or lever acts on
             * @enum {string}
             */
            premiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
            /** @example all_cause_mortality_five_year */
            target?: string;
            /** @enum {string} */
            state: "candidate" | "awaiting_validation" | "validated" | "in_production" | "withdrawn";
            featureNames?: string[];
            productionJurisdictions?: string[];
            /** @enum {string} */
            buildMethod?: "manual" | "automated_search" | "vendor_supplied" | "reverse_engineered";
            submittedBy?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ListEnvelopeRiskModel: {
            data: {
                items: {
                    id: string;
                    name: string;
                    /**
                     * @description The term of the price a model or lever acts on
                     * @enum {string}
                     */
                    premiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
                    /** @example all_cause_mortality_five_year */
                    target?: string;
                    /** @enum {string} */
                    state: "candidate" | "awaiting_validation" | "validated" | "in_production" | "withdrawn";
                    featureNames?: string[];
                    productionJurisdictions?: string[];
                    /** @enum {string} */
                    buildMethod?: "manual" | "automated_search" | "vendor_supplied" | "reverse_engineered";
                    submittedBy?: string;
                    /** Format: date-time */
                    submittedAt?: string;
                    /** Format: date-time */
                    createdAt?: string;
                    /** Format: date-time */
                    updatedAt?: string;
                }[];
                nextCursor?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        RiskModelCreate: {
            name: string;
            /**
             * @description The term of the price a model or lever acts on
             * @enum {string}
             */
            premiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
            target: string;
            featureNames: string[];
            buildMethod?: string;
            submittedBy?: string;
        };
        DataEnvelopeRiskModel: {
            data: {
                id: string;
                name: string;
                /**
                 * @description The term of the price a model or lever acts on
                 * @enum {string}
                 */
                premiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
                /** @example all_cause_mortality_five_year */
                target?: string;
                /** @enum {string} */
                state: "candidate" | "awaiting_validation" | "validated" | "in_production" | "withdrawn";
                featureNames?: string[];
                productionJurisdictions?: string[];
                /** @enum {string} */
                buildMethod?: "manual" | "automated_search" | "vendor_supplied" | "reverse_engineered";
                submittedBy?: string;
                /** Format: date-time */
                submittedAt?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ModelValidationCreate: {
            /** @enum {string} */
            outcome: "approved" | "approved_with_conditions" | "rejected";
            validatedBy: string;
            permittedJurisdictions?: string[];
            blockedJurisdictions?: string[];
            blockedFactors?: string[];
            stabilityAssessment?: string;
            conditions?: string[];
        };
        ModelValidation: {
            modelId: string;
            /** @enum {string} */
            outcome: "approved" | "approved_with_conditions" | "rejected";
            validatedBy: string;
            permittedJurisdictions?: string[];
            blockedJurisdictions?: string[];
            blockedFactors?: string[];
            stabilityAssessment?: string;
            conditions?: string[];
            /** Format: date-time */
            validatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        DataEnvelopeModelValidation: {
            data: {
                modelId: string;
                /** @enum {string} */
                outcome: "approved" | "approved_with_conditions" | "rejected";
                validatedBy: string;
                permittedJurisdictions?: string[];
                blockedJurisdictions?: string[];
                blockedFactors?: string[];
                stabilityAssessment?: string;
                conditions?: string[];
                /** Format: date-time */
                validatedAt?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ValidationQueue: {
            awaitingValidation?: number;
            /** Format: float */
            medianAgeDays?: number;
            /** Format: float */
            oldestAgeDays?: number;
            byPremiumTerm?: {
                [key: string]: number;
            };
            validationCapacityPerMonth?: number;
            flaggedAsOperationalRisk?: boolean;
        };
        DataEnvelopeValidationQueue: {
            data: {
                awaitingValidation?: number;
                /** Format: float */
                medianAgeDays?: number;
                /** Format: float */
                oldestAgeDays?: number;
                byPremiumTerm?: {
                    [key: string]: number;
                };
                validationCapacityPerMonth?: number;
                flaggedAsOperationalRisk?: boolean;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        ModelId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFactorPermits: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                jurisdiction?: string;
                position?: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
                dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-factor, per-jurisdiction permitted-use positions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                /** @example residential_postcode_mortality_index */
                                factor: string;
                                /** @enum {string} */
                                dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
                                jurisdiction: string;
                                /** @enum {string} */
                                position: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
                                /** @description Whether the factor proxies a protected characteristic */
                                proxyRiskAssessment?: string;
                                /** @description Statutory or moratorium position for genetic and similar data */
                                restrictedHealthDataBasis?: string;
                                explainableToApplicant?: boolean;
                                conditions?: string[];
                                officerId?: string;
                                /** Format: date-time */
                                reviewedAt?: string;
                                /** Format: date */
                                nextReviewDue?: string;
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recordFactorPermit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    factor: string;
                    /** @enum {string} */
                    dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
                    jurisdiction: string;
                    /** @enum {string} */
                    position: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
                    proxyRiskAssessment?: string;
                    restrictedHealthDataBasis?: string;
                    explainableToApplicant?: boolean;
                    conditions?: string[];
                    officerId: string;
                };
            };
        };
        responses: {
            /** @description Position recorded by a named compliance officer */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @example residential_postcode_mortality_index */
                            factor: string;
                            /** @enum {string} */
                            dataCategory?: "connected_life" | "connected_car" | "connected_home" | "connected_finance" | "medical_evidence" | "genetic" | "epigenetic" | "microbiome" | "geographic" | "declared_lifestyle" | "population_table";
                            jurisdiction: string;
                            /** @enum {string} */
                            position: "permitted" | "permitted_with_conditions" | "prohibited" | "undetermined";
                            /** @description Whether the factor proxies a protected characteristic */
                            proxyRiskAssessment?: string;
                            /** @description Statutory or moratorium position for genetic and similar data */
                            restrictedHealthDataBasis?: string;
                            explainableToApplicant?: boolean;
                            conditions?: string[];
                            officerId?: string;
                            /** Format: date-time */
                            reviewedAt?: string;
                            /** Format: date */
                            nextReviewDue?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listRiskModels: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                premiumTerm?: "expected_claims" | "loading_for_risk" | "loading_for_expense";
                state?: "candidate" | "awaiting_validation" | "validated" | "in_production" | "withdrawn";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models with declared premium term and validation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                name: string;
                                /**
                                 * @description The term of the price a model or lever acts on
                                 * @enum {string}
                                 */
                                premiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
                                /** @example all_cause_mortality_five_year */
                                target?: string;
                                /** @enum {string} */
                                state: "candidate" | "awaiting_validation" | "validated" | "in_production" | "withdrawn";
                                featureNames?: string[];
                                productionJurisdictions?: string[];
                                /** @enum {string} */
                                buildMethod?: "manual" | "automated_search" | "vendor_supplied" | "reverse_engineered";
                                submittedBy?: string;
                                /** Format: date-time */
                                submittedAt?: string;
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    submitRiskModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /**
                     * @description The term of the price a model or lever acts on
                     * @enum {string}
                     */
                    premiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
                    target: string;
                    featureNames: string[];
                    buildMethod?: string;
                    submittedBy?: string;
                };
            };
        };
        responses: {
            /** @description Model queued for validation with its declared premium term */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /**
                             * @description The term of the price a model or lever acts on
                             * @enum {string}
                             */
                            premiumTerm: "expected_claims" | "loading_for_risk" | "loading_for_expense";
                            /** @example all_cause_mortality_five_year */
                            target?: string;
                            /** @enum {string} */
                            state: "candidate" | "awaiting_validation" | "validated" | "in_production" | "withdrawn";
                            featureNames?: string[];
                            productionJurisdictions?: string[];
                            /** @enum {string} */
                            buildMethod?: "manual" | "automated_search" | "vendor_supplied" | "reverse_engineered";
                            submittedBy?: string;
                            /** Format: date-time */
                            submittedAt?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Rejected because no premium term was declared. A model that cannot name the term of the price it acts on may not be deployed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    validateRiskModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    outcome: "approved" | "approved_with_conditions" | "rejected";
                    validatedBy: string;
                    permittedJurisdictions?: string[];
                    blockedJurisdictions?: string[];
                    blockedFactors?: string[];
                    stabilityAssessment?: string;
                    conditions?: string[];
                };
            };
        };
        responses: {
            /** @description Validation outcome and production permission by jurisdiction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            modelId: string;
                            /** @enum {string} */
                            outcome: "approved" | "approved_with_conditions" | "rejected";
                            validatedBy: string;
                            permittedJurisdictions?: string[];
                            blockedJurisdictions?: string[];
                            blockedFactors?: string[];
                            stabilityAssessment?: string;
                            conditions?: string[];
                            /** Format: date-time */
                            validatedAt?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getValidationQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue depth and ageing for candidate models, reported as operational risk since model production outpaces validation capacity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            awaitingValidation?: number;
                            /** Format: float */
                            medianAgeDays?: number;
                            /** Format: float */
                            oldestAgeDays?: number;
                            byPremiumTerm?: {
                                [key: string]: number;
                            };
                            validationCapacityPerMonth?: number;
                            flaggedAsOperationalRisk?: boolean;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
