/**
 * Identity DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Identity Domain Module - Composition root
 *
 * DDD: Composition root for identity domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApiKeyRepositoryAdapter,
  DisableRepositoryAdapter,
  EnableRepositoryAdapter,
  LoginRepositoryAdapter,
  LogoutRepositoryAdapter,
  MeRepositoryAdapter,
  RefreshRepositoryAdapter,
  UserRepositoryAdapter,
} from "@loadline/adapters/identity";
import { getIdGeneratorService } from "@loadline/adapters";
import type { AdapterDynamoDBClient } from "@loadline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateTenantApiKey,
  ExecuteCreateTenantUser,
  ExecuteDisableTenantUser,
  ExecuteEnableTenantUser,
  ExecuteGetOperatorMe,
  ExecuteGetTenantApiKey,
  ExecuteGetTenantUser,
  ExecuteListTenantApiKeys,
  ExecuteListTenantUsers,
  ExecuteOperatorLogin,
  ExecuteOperatorLogout,
  ExecuteOperatorRefresh,
  ExecuteRevokeTenantApiKey,
  ExecuteUpdateOperatorMe,
  ExecuteUpdateTenantUser,
} from "@loadline/services/identity/usecases";
// Ports (interfaces)
import type {
  ApiKeyRepository,
  DisableRepository,
  EnableRepository,
  LoginRepository,
  LogoutRepository,
  MeRepository,
  RefreshRepository,
  UserRepository,
} from "@loadline/services/identity/ports";

export interface IdentityDomainModule {
  repos: {
    apiKeys: ApiKeyRepository;
    disables: DisableRepository;
    enables: EnableRepository;
    logins: LoginRepository;
    logouts: LogoutRepository;
    mes: MeRepository;
    refreshes: RefreshRepository;
    users: UserRepository;
  };
  useCases: {
    apiKeys: {
      create: ExecuteCreateTenantApiKey;
      get: ExecuteRevokeTenantApiKey;
      list: ExecuteListTenantApiKeys;
    };
    disables: {
      update: ExecuteDisableTenantUser;
    };
    enables: {
      update: ExecuteEnableTenantUser;
    };
    logins: {
      get: ExecuteOperatorLogin;
    };
    logouts: {
      get: ExecuteOperatorLogout;
    };
    mes: {
      get: ExecuteGetOperatorMe;
      update: ExecuteUpdateOperatorMe;
    };
    refreshes: {
      get: ExecuteOperatorRefresh;
    };
    users: {
      create: ExecuteCreateTenantUser;
      get: ExecuteGetTenantUser;
      list: ExecuteListTenantUsers;
      update: ExecuteUpdateTenantUser;
    };
  };
}

export function buildIdentityDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): IdentityDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      apiKeys?: ApiKeyRepository;
      disables?: DisableRepository;
      enables?: EnableRepository;
      logins?: LoginRepository;
      logouts?: LogoutRepository;
      mes?: MeRepository;
      refreshes?: RefreshRepository;
      users?: UserRepository;
    } = {};

    obj.apiKeys = new ApiKeyRepositoryAdapter(dynamoClient);
    obj.disables = new DisableRepositoryAdapter(dynamoClient);
    obj.enables = new EnableRepositoryAdapter(dynamoClient);
    obj.logins = new LoginRepositoryAdapter(dynamoClient);
    obj.logouts = new LogoutRepositoryAdapter(dynamoClient);
    obj.mes = new MeRepositoryAdapter(dynamoClient);
    obj.refreshes = new RefreshRepositoryAdapter(dynamoClient);
    obj.users = new UserRepositoryAdapter(dynamoClient);
    return {
      apiKeys: obj.apiKeys!,
      disables: obj.disables!,
      enables: obj.enables!,
      logins: obj.logins!,
      logouts: obj.logouts!,
      mes: obj.mes!,
      refreshes: obj.refreshes!,
      users: obj.users!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    apiKeys: {
      create: new ExecuteCreateTenantApiKey(executionContext, idGenerator, repos.apiKeys),
      get: new ExecuteRevokeTenantApiKey(executionContext, idGenerator, repos.apiKeys),
      list: new ExecuteListTenantApiKeys(executionContext, idGenerator, repos.apiKeys),
    },
    disables: {
      update: new ExecuteDisableTenantUser(executionContext, idGenerator, repos.disables),
    },
    enables: {
      update: new ExecuteEnableTenantUser(executionContext, idGenerator, repos.enables),
    },
    logins: {
      get: new ExecuteOperatorLogin(executionContext, idGenerator, repos.logins),
    },
    logouts: {
      get: new ExecuteOperatorLogout(executionContext, idGenerator, repos.logouts),
    },
    mes: {
      get: new ExecuteGetOperatorMe(executionContext, idGenerator, repos.mes),
      update: new ExecuteUpdateOperatorMe(executionContext, idGenerator, repos.mes),
    },
    refreshes: {
      get: new ExecuteOperatorRefresh(executionContext, idGenerator, repos.refreshes),
    },
    users: {
      create: new ExecuteCreateTenantUser(executionContext, idGenerator, repos.users),
      get: new ExecuteGetTenantUser(executionContext, idGenerator, repos.users),
      list: new ExecuteListTenantUsers(executionContext, idGenerator, repos.users),
      update: new ExecuteUpdateTenantUser(executionContext, idGenerator, repos.users),
    },
  };
  return { repos, useCases: useCases as IdentityDomainModule["useCases"] };
}
