/**
 * SettleClaimAutomatically handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { settleClaimAutomatically } from "@loadline/api-server/domains/claims/handlers";
import type { ClaimsDDDDependencies } from "@loadline/api-server/domains/claims";
import { createAutomaticSettlement as createAutomaticSettlementEntity } from "@loadline/factories/claims";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { CLAIMS_USE_CASES } from "../__factories__/use-cases.js";

describe("SettleClaimAutomatically", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ClaimsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ClaimsDDDDependencies>(
      CLAIMS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createAutomaticSettlementEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { id: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSettleClaimAutomatically, "execute").mockResolvedValue(useCaseResult);

    await settleClaimAutomatically(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSettleClaimAutomatically.execute).toHaveBeenCalledWith(expect.objectContaining({ id: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
