/**
 * VariationEnvelopeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VariationEnvelopeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VariationEnvelopeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VariationEnvelopeRepository,
} from "@loadline/services/composition";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VariationEnvelopeRepositoryDdb } from "./variation-envelope-repository.ddb.js";

/**
 * VariationEnvelopeRepositoryAdapter
 *
 * Implements VariationEnvelopeRepository port for infrastructure layer.
 */
export class VariationEnvelopeRepositoryAdapter implements VariationEnvelopeRepository {
  private readonly ddb: VariationEnvelopeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VariationEnvelopeRepositoryDdb(this.dynamoClient);
  }

  async listVariationEnvelopes(input: Parameters<VariationEnvelopeRepository['listVariationEnvelopes']>[0]): Promise<Awaited<ReturnType<VariationEnvelopeRepository['listVariationEnvelopes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listVariationEnvelopes(input);
  }

  async setVariationEnvelope(input: Parameters<VariationEnvelopeRepository['setVariationEnvelope']>[0]): Promise<Awaited<ReturnType<VariationEnvelopeRepository['setVariationEnvelope']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setVariationEnvelope(input);
  }
}
