/**
 * Handlers for ExpenseMeasurement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ClaimsDomainModule } from "../dependencies/claims-ddd.dependencies.js";
import type { GetExpenseMeasurementInput } from "@loadline/services/claims";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/claims/expense-measurements
 * Operation: getExpenseMeasurement
 */
export async function getExpenseMeasurement(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { productCode?: string | string[], period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ClaimsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetExpenseMeasurementInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.expenseMeasurements.get.execute(input);
  return reply.code(200).send(result);
}


