/**
 * Handlers for FraudReferral
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ClaimsDomainModule } from "../dependencies/claims-ddd.dependencies.js";
import type { RaiseFraudReferralInput } from "@loadline/services/claims";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/claims/fraud-referrals
 * Operation: raiseFraudReferral
 */
export async function raiseFraudReferral(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ClaimsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RaiseFraudReferralInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.fraudReferrals.get.execute(input);
  return reply.code(201).send(result);
}


