/**
 * Routes for ApiKey
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createTenantApiKey, getTenantApiKey, listTenantApiKeys, revokeTenantApiKey } from "../handlers/api-key.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function apiKeyRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/api-keys (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/api-keys",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await createTenantApiKey(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/api-keys (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/api-keys",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await listTenantApiKeys(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/api-keys/{keyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/api-keys/:keyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { keyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await getTenantApiKey(request, reply, deps);
      });
    }
  );


  // DELETE /v0/tenants/me/api-keys/{keyId} (unscoped; scope set for security middleware)
  fastify.delete(
    "/v0/tenants/me/api-keys/:keyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { keyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await revokeTenantApiKey(request, reply, deps);
      });
    }
  );


}
