/**
 * Routes for Disable
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { disableTenantUser } from "../handlers/disable.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function disableRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/users/{userId}/disable (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/users/:userId/disable",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { userId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await disableTenantUser(request, reply, deps);
      });
    }
  );


}
