/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { loginRoutes } from "./login.routes.js";
export { logoutRoutes } from "./logout.routes.js";
export { meRoutes } from "./me.routes.js";
export { refreshRoutes } from "./refresh.routes.js";
export { apiKeyRoutes } from "./api-key.routes.js";
export { disableRoutes } from "./disable.routes.js";
export { enableRoutes } from "./enable.routes.js";
export { userRoutes } from "./user.routes.js";
