/**
 * Routes for User
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createTenantUser, getTenantUser, listTenantUsers, updateTenantUser } from "../handlers/user.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function userRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/users (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/users",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await createTenantUser(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/users (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/users",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await listTenantUsers(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/users/{userId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/users/:userId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { userId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await getTenantUser(request, reply, deps);
      });
    }
  );


  // PATCH /v0/tenants/me/users/{userId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v0/tenants/me/users/:userId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { userId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIdentityDependenciesForRequest();
        await updateTenantUser(request, reply, deps);
      });
    }
  );


}
