/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @loadline/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@loadline/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@loadline/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@loadline/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@loadline/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@loadline/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _claims from "./claims/index.js";
import * as _composition from "./composition/index.js";
import * as _engagement from "./engagement/index.js";
import * as _experience from "./experience/index.js";
import * as _identity from "./identity/index.js";
import * as _permitting from "./permitting/index.js";
import * as _reinsurance from "./reinsurance/index.js";
import * as _scoring from "./scoring/index.js";

// Export as namespaces
export const _shared = __shared;
export const claims = _claims;
export const composition = _composition;
export const engagement = _engagement;
export const experience = _experience;
export const identity = _identity;
export const permitting = _permitting;
export const reinsurance = _reinsurance;
export const scoring = _scoring;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@loadline/core"; activity.types.*
//   - Direct exports: import * from "@loadline/core/activity/types/index.js"
//   - Direct exports: import * from "@loadline/core/activity/repositories/index.js"
//   - Direct exports: import * from "@loadline/core/activity/models/index.js"
//   - Direct exports: import * from "@loadline/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Claims Service
export { schemas as ClaimsSchemas } from "./claims/schemas/claims.schemas.js";

// Composition Service
export { schemas as CompositionSchemas } from "./composition/schemas/composition.schemas.js";

// Engagement Service
export { schemas as EngagementSchemas } from "./engagement/schemas/engagement.schemas.js";

// Experience Service
export { schemas as ExperienceSchemas } from "./experience/schemas/experience.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Permitting Service
export { schemas as PermittingSchemas } from "./permitting/schemas/permitting.schemas.js";

// Reinsurance Service
export { schemas as ReinsuranceSchemas } from "./reinsurance/schemas/reinsurance.schemas.js";

// Scoring Service
export { schemas as ScoringSchemas } from "./scoring/schemas/scoring.schemas.js";

