/**
 * Repository interface for ExpenseMeasurement
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExpenseMeasurementEntity
} from "../models/expense-measurement.entity.js";
import type {
  GetExpenseMeasurementParams
} from "../types/index.js";
/**
 * ExpenseMeasurementRepository Interface
 */
export interface ExpenseMeasurementRepository extends ReadRepository<ExpenseMeasurementEntity, string, GetExpenseMeasurementParams> {

}
