/**
 * ExecuteResolveConsentState - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteResolveConsentState Use Case
 *
 * DDD: Application use case for get Consent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ResolveConsentStateInput, ResolveConsentStateOutput } from "../dto/consent.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { ConsentRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteResolveConsentState {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly consent: ConsentRepository
  ) {}

  async execute(input: ResolveConsentStateInput): Promise<ResolveConsentStateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scoId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).riskSubjectId) {
      throw new ValidationError("riskSubjectId is required");
    }
    const risksubjectId = (input as any).riskSubjectId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.consent.resolveConsentState({ riskSubjectId: risksubjectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${risksubjectId}`);
    }

    return entity as ResolveConsentStateOutput;
  }
}
