/**
 * Repository interface for ValidationQueue
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ValidationQueueEntity
} from "../models/validation-queue.entity.js";
/**
 * ValidationQueueRepository Interface
 */
export interface ValidationQueueRepository extends ReadRepository<ValidationQueueEntity, string, Record<string, never>> {

}
