/**
 * GetTenantApiKey handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTenantApiKey } from "@loadline/api-server/domains/identity/handlers";
import type { IdentityDDDDependencies } from "@loadline/api-server/domains/identity";
import { createApiKey as createApiKeyEntity } from "@loadline/factories/identity";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { IDENTITY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTenantApiKey", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IdentityDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IdentityDDDDependencies>(
      IDENTITY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createApiKeyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTenantApiKey, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { keyId: entity.id };

    await getTenantApiKey(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTenantApiKey.execute).toHaveBeenCalledWith(expect.objectContaining({ keyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { keyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetTenantApiKey, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getTenantApiKey(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
