/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-tenant-api-key.handler.test.js";
export * from "./get-tenant-api-key.handler.test.js";
export * from "./list-tenant-api-keys.handler.test.js";
export * from "./revoke-tenant-api-key.handler.test.js";
