/**
 * RevokeTenantApiKey handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { revokeTenantApiKey } from "@loadline/api-server/domains/identity/handlers";
import type { IdentityDDDDependencies } from "@loadline/api-server/domains/identity";
import { createApiKey as createApiKeyEntity } from "@loadline/factories/identity";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { IDENTITY_USE_CASES } from "../__factories__/use-cases.js";

describe("RevokeTenantApiKey", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IdentityDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IdentityDDDDependencies>(
      IDENTITY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 204 on successful deletion", async () => {
    const entity = createApiKeyEntity({ orgId });
    mockRequest.params = { keyId: entity.id };
    
    vi.spyOn(mockDeps.executeRevokeTenantApiKey, "execute").mockResolvedValue(undefined);

    await revokeTenantApiKey(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRevokeTenantApiKey.execute).toHaveBeenCalledWith(expect.objectContaining({ keyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(204);
  });

});
