/**
 * ExecuteRequestHumanReview - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRequestHumanReview Use Case
 *
 * DDD: Application use case for get Review.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RequestHumanReviewInput, RequestHumanReviewOutput } from "../dto/review.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { ReviewRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteRequestHumanReview {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly review: ReviewRepository
  ) {}

  async execute(input: RequestHumanReviewInput): Promise<RequestHumanReviewOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.reiId();

    // All field names extracted from OpenAPI spec: grounds, requestedBy
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).decisionId) {
      throw new ValidationError("decisionId is required");
    }
    const decisionId = (input as any).decisionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.review.requestHumanReview({ decisionId: decisionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${decisionId}`);
    }

    return entity as RequestHumanReviewOutput;
  }
}
