/**
 * ExecuteGetCessionExperience - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCessionExperience Use Case
 *
 * DDD: Application use case for get CessionExperience.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCessionExperienceInput, GetCessionExperienceOutput } from "../dto/cession-experience.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { CessionExperienceRepository } from "../ports/index.js";
import { NotFoundError } from "../errors/index.js";

export class ExecuteGetCessionExperience {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cessionExperience: CessionExperienceRepository
  ) {}

  async execute(input: GetCessionExperienceInput): Promise<GetCessionExperienceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.reiId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.cessionExperience.getCessionExperience({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetCessionExperienceOutput;
  }
}
