/**
 * Programme Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ProgrammeEntity } from "@loadline/core/engagement/models/index.js";
import { engagementSchemas } from "@loadline/core/engagement";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "eng";

export function createProgramme(overrides: Partial<ProgrammeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    premiumTermTargeted: overrides.premiumTermTargeted ?? "expected_claims",
    state: overrides.state ?? "design",
    ...overrides,
  };

  return engagementSchemas.EngagementProgramme.parse(raw);
}

export function programmeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createProgramme(overrides));
}
