/**
 * Validation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Validation DTOs
 *
 * DDD: Application DTOs for Validation use cases.
 */

import type { ValidateRiskModelParams, ValidateRiskModelRequestInput } from "@loadline/core/permitting/types";

export type ValidateRiskModelInput = ValidateRiskModelParams & ValidateRiskModelRequestInput;

export type ValidateRiskModelOutput = {};
