/**
 * Calibration Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CalibrationEntity } from "@loadline/core/composition/models/index.js";
import { compositionSchemas } from "@loadline/core/composition";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cmp";

export function createCalibration(overrides: Partial<CalibrationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    approvedBy: overrides.approvedBy ?? faker.lorem.word(),
    calibratedPrice: overrides.calibratedPrice ?? {
      amount: 0,
      currency: ""
    },
    compositionId: overrides.compositionId ?? faker.string.uuid(),
    rationale: overrides.rationale ?? "competitive_position",
    ...overrides,
  };

  return compositionSchemas.CommercialCalibration.parse(raw);
}

export function calibrationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCalibration(overrides));
}
