/**
 * ExecuteListExperienceObservations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListExperienceObservations Use Case
 *
 * DDD: Application use case for list Observation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListExperienceObservationsInput, ListExperienceObservationsOutput } from "../dto/observation.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { ObservationRepository } from "../ports/index.js";

export class ExecuteListExperienceObservations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly observation: ObservationRepository
  ) {}

  async execute(input: ListExperienceObservationsInput): Promise<ListExperienceObservationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.expId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.observation.listExperienceObservations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListExperienceObservationsOutput;
  }
}
