/**
 * ExecuteDefineCohort - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDefineCohort Use Case
 *
 * DDD: Application use case for get Cohort.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DefineCohortInput, DefineCohortOutput } from "../dto/cohort.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { CohortRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteDefineCohort {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cohort: CohortRepository
  ) {}

  async execute(input: DefineCohortInput): Promise<DefineCohortOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.expId();

    // All field names extracted from OpenAPI spec: cohortKind, comparableCohortId, matchedOn, observationWindowMonths, programmeId, selectionSeparationMethod
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).comparableCohortId) {
      throw new ValidationError("comparableCohortId is required");
    }
    const comparablecohortId = (input as any).comparableCohortId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.cohort.defineCohort({ comparableCohortId: comparablecohortId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${comparablecohortId}`);
    }

    return entity as DefineCohortOutput;
  }
}
