/**
 * ExecuteCreditExpectedClaimsSaving - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreditExpectedClaimsSaving Use Case
 *
 * DDD: Application use case for get SavingsCredit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreditExpectedClaimsSavingInput, CreditExpectedClaimsSavingOutput } from "../dto/savings-credit.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { SavingsCreditRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteCreditExpectedClaimsSaving {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly savingsCredit: SavingsCreditRepository
  ) {}

  async execute(input: CreditExpectedClaimsSavingInput): Promise<CreditExpectedClaimsSavingOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.expId();

    // All field names extracted from OpenAPI spec: appliesFromPeriod, behaviouralEffect, cohortId, creditedBasisPoints, premiumTerm, selectionEffectRemoved, signedOffBy
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).cohortId) {
      throw new ValidationError("cohortId is required");
    }
    const cohortId = (input as any).cohortId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.savingsCredit.creditExpectedClaimsSaving({ cohortId: cohortId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${cohortId}`);
    }

    return entity as CreditExpectedClaimsSavingOutput;
  }
}
