/**
 * ExecuteListCohortDefinitions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCohortDefinitions Use Case
 *
 * DDD: Application use case for list Cohort.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCohortDefinitionsInput, ListCohortDefinitionsOutput } from "../dto/cohort.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { CohortRepository } from "../ports/index.js";

export class ExecuteListCohortDefinitions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cohort: CohortRepository
  ) {}

  async execute(input: ListCohortDefinitionsInput): Promise<ListCohortDefinitionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.expId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.cohort.listCohortDefinitions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCohortDefinitionsOutput;
  }
}
