/**
 * Consent Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ConsentEntity } from "@loadline/core/scoring/models/index.js";
import { scoringSchemas } from "@loadline/core/scoring";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "sco";

export function createConsent(overrides: Partial<ConsentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dataCategory: overrides.dataCategory ?? "connected_life",
    riskSubjectId: overrides.riskSubjectId ?? faker.string.uuid(),
    state: overrides.state ?? "granted",
    ...overrides,
  };

  return scoringSchemas.ConsentRecord.parse(raw);
}

export function consentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createConsent(overrides));
}
