/**
 * Permitting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Permitting Domain Module - Composition root
 *
 * DDD: Composition root for permitting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  FactorPermitRepositoryAdapter,
  PermittingModelRepositoryAdapter,
  ValidationQueueRepositoryAdapter,
  ValidationRepositoryAdapter,
} from "@loadline/adapters/permitting";
import { getIdGeneratorService } from "@loadline/adapters";
import type { AdapterDynamoDBClient } from "@loadline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetValidationQueue,
  ExecuteListFactorPermits,
  ExecuteListRiskModels,
  ExecuteRecordFactorPermit,
  ExecuteSubmitRiskModel,
  ExecuteValidateRiskModel,
} from "@loadline/services/permitting/usecases";
// Ports (interfaces)
import type {
  FactorPermitRepository,
  PermittingModelRepository,
  ValidationQueueRepository,
  ValidationRepository,
} from "@loadline/services/permitting/ports";

export interface PermittingDomainModule {
  repos: {
    factorPermits: FactorPermitRepository;
    models: PermittingModelRepository;
    validationQueues: ValidationQueueRepository;
    validations: ValidationRepository;
  };
  useCases: {
    factorPermits: {
      get: ExecuteRecordFactorPermit;
      list: ExecuteListFactorPermits;
    };
    models: {
      create: ExecuteSubmitRiskModel;
      list: ExecuteListRiskModels;
    };
    validationQueues: {
      get: ExecuteGetValidationQueue;
    };
    validations: {
      get: ExecuteValidateRiskModel;
    };
  };
}

export function buildPermittingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PermittingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      factorPermits?: FactorPermitRepository;
      models?: PermittingModelRepository;
      validationQueues?: ValidationQueueRepository;
      validations?: ValidationRepository;
    } = {};

    obj.factorPermits = new FactorPermitRepositoryAdapter(dynamoClient);
    obj.models = new PermittingModelRepositoryAdapter(dynamoClient);
    obj.validationQueues = new ValidationQueueRepositoryAdapter(dynamoClient);
    obj.validations = new ValidationRepositoryAdapter(dynamoClient);
    return {
      factorPermits: obj.factorPermits!,
      models: obj.models!,
      validationQueues: obj.validationQueues!,
      validations: obj.validations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    factorPermits: {
      get: new ExecuteRecordFactorPermit(executionContext, idGenerator, repos.factorPermits),
      list: new ExecuteListFactorPermits(executionContext, idGenerator, repos.factorPermits),
    },
    models: {
      create: new ExecuteSubmitRiskModel(executionContext, idGenerator, repos.models),
      list: new ExecuteListRiskModels(executionContext, idGenerator, repos.models),
    },
    validationQueues: {
      get: new ExecuteGetValidationQueue(executionContext, idGenerator, repos.validationQueues),
    },
    validations: {
      get: new ExecuteValidateRiskModel(executionContext, idGenerator, repos.validations),
    },
  };
  return { repos, useCases: useCases as PermittingDomainModule["useCases"] };
}
