/**
 * RequestHumanReview handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { requestHumanReview } from "@loadline/api-server/domains/reinsurance/handlers";
import type { ReinsuranceDDDDependencies } from "@loadline/api-server/domains/reinsurance";
import { createReview as createReviewEntity } from "@loadline/factories/reinsurance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { REINSURANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("RequestHumanReview", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReinsuranceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReinsuranceDDDDependencies>(
      REINSURANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createReviewEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRequestHumanReview, "execute").mockResolvedValue(useCaseResult);

    await requestHumanReview(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRequestHumanReview.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
