/**
 * AutomaticSettlementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AutomaticSettlementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AutomaticSettlementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AutomaticSettlementRepository,
} from "@loadline/services/claims";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AutomaticSettlementRepositoryDdb } from "./automatic-settlement-repository.ddb.js";

/**
 * AutomaticSettlementRepositoryAdapter
 *
 * Implements AutomaticSettlementRepository port for infrastructure layer.
 */
export class AutomaticSettlementRepositoryAdapter implements AutomaticSettlementRepository {
  private readonly ddb: AutomaticSettlementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AutomaticSettlementRepositoryDdb(this.dynamoClient);
  }

  async settleClaimAutomatically(input: Parameters<AutomaticSettlementRepository['settleClaimAutomatically']>[0]): Promise<Awaited<ReturnType<AutomaticSettlementRepository['settleClaimAutomatically']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.settleClaimAutomatically(input);
  }
}
