/**
 * FraudReferralRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FraudReferralRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FraudReferralRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FraudReferralRepository,
} from "@loadline/services/claims";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FraudReferralRepositoryDdb } from "./fraud-referral-repository.ddb.js";

/**
 * FraudReferralRepositoryAdapter
 *
 * Implements FraudReferralRepository port for infrastructure layer.
 */
export class FraudReferralRepositoryAdapter implements FraudReferralRepository {
  private readonly ddb: FraudReferralRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FraudReferralRepositoryDdb(this.dynamoClient);
  }

  async raiseFraudReferral(input: Parameters<FraudReferralRepository['raiseFraudReferral']>[0]): Promise<Awaited<ReturnType<FraudReferralRepository['raiseFraudReferral']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.raiseFraudReferral(input);
  }
}
