/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./automatic-settlement-repository.ddb.js";
export * from "./expense-measurement-repository.ddb.js";
export * from "./fraud-referral-repository.ddb.js";
export * from "./automatic-settlement-repository.adapter.js";
export * from "./expense-measurement-repository.adapter.js";
export * from "./fraud-referral-repository.adapter.js";
