/**
 * FrequencyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FrequencyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FrequencyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FrequencyRepository,
} from "@loadline/services/engagement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FrequencyRepositoryDdb } from "./frequency-repository.ddb.js";

/**
 * FrequencyRepositoryAdapter
 *
 * Implements FrequencyRepository port for infrastructure layer.
 */
export class FrequencyRepositoryAdapter implements FrequencyRepository {
  private readonly ddb: FrequencyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FrequencyRepositoryDdb(this.dynamoClient);
  }

  async getTouchpointFrequency(input: Parameters<FrequencyRepository['getTouchpointFrequency']>[0]): Promise<Awaited<ReturnType<FrequencyRepository['getTouchpointFrequency']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTouchpointFrequency(input);
  }
}
