/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./frequency-repository.ddb.js";
export * from "./programme-repository.ddb.js";
export * from "./touchpoint-repository.ddb.js";
export * from "./frequency-repository.adapter.js";
export * from "./programme-repository.adapter.js";
export * from "./touchpoint-repository.adapter.js";
