/**
 * ProgrammeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProgrammeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProgrammeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProgrammeRepository,
} from "@loadline/services/engagement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProgrammeRepositoryDdb } from "./programme-repository.ddb.js";

/**
 * ProgrammeRepositoryAdapter
 *
 * Implements ProgrammeRepository port for infrastructure layer.
 */
export class ProgrammeRepositoryAdapter implements ProgrammeRepository {
  private readonly ddb: ProgrammeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProgrammeRepositoryDdb(this.dynamoClient);
  }

  async listEngagementProgrammes(input: Parameters<ProgrammeRepository['listEngagementProgrammes']>[0]): Promise<Awaited<ReturnType<ProgrammeRepository['listEngagementProgrammes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEngagementProgrammes(input);
  }

  async createEngagementProgramme(input: Parameters<ProgrammeRepository['createEngagementProgramme']>[0]): Promise<Awaited<ReturnType<ProgrammeRepository['createEngagementProgramme']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createEngagementProgramme(input);
  }
}
