/**
 * TouchpointRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TouchpointRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TouchpointRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TouchpointRepository,
} from "@loadline/services/engagement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TouchpointRepositoryDdb } from "./touchpoint-repository.ddb.js";

/**
 * TouchpointRepositoryAdapter
 *
 * Implements TouchpointRepository port for infrastructure layer.
 */
export class TouchpointRepositoryAdapter implements TouchpointRepository {
  private readonly ddb: TouchpointRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TouchpointRepositoryDdb(this.dynamoClient);
  }

  async recordTouchpointEvent(input: Parameters<TouchpointRepository['recordTouchpointEvent']>[0]): Promise<Awaited<ReturnType<TouchpointRepository['recordTouchpointEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordTouchpointEvent(input);
  }
}
