/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Composition Domain Use Cases
 * 
 * List of all use case names for the composition domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const COMPOSITION_USE_CASES = [
  "executeApplyCommercialCalibration",
  "executeComposePremium",
  "executeIssuePriceOffer",
  "executeListVariationEnvelopes",
  "executeSetVariationEnvelope"
] as const;
