/**
 * Routes for Frequency
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getTouchpointFrequency } from "../handlers/frequency.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function frequencyRoutes(fastify: FastifyInstance) {
  // GET /v1/engagement/enrolments/{enrolmentId}/frequency (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/engagement/enrolments/:enrolmentId/frequency",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { enrolmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEngagementDependenciesForRequest();
        await getTouchpointFrequency(request, reply, deps);
      });
    }
  );


}
