/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { programmeRoutes } from "./programme.routes.js";
export { touchpointRoutes } from "./touchpoint.routes.js";
export { frequencyRoutes } from "./frequency.routes.js";
