/**
 * FraudReferral Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { FraudReferralEntity } from "@loadline/core/claims/models/index.js";
import { claimsSchemas } from "@loadline/core/claims";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "clm";

export function createFraudReferral(overrides: Partial<FraudReferralEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    claimReference: overrides.claimReference ?? faker.lorem.word(),
    indicators: overrides.indicators ?? [],
    ...overrides,
  };

  return claimsSchemas.FraudReferral.parse(raw);
}

export function fraudReferralBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFraudReferral(overrides));
}
