/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildClaimsDomainModule } from "./claims/dependencies/claims-ddd.dependencies.js";
export { buildCompositionDomainModule } from "./composition/dependencies/composition-ddd.dependencies.js";
export { buildEngagementDomainModule } from "./engagement/dependencies/engagement-ddd.dependencies.js";
export { buildExperienceDomainModule } from "./experience/dependencies/experience-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildPermittingDomainModule } from "./permitting/dependencies/permitting-ddd.dependencies.js";
export { buildReinsuranceDomainModule } from "./reinsurance/dependencies/reinsurance-ddd.dependencies.js";
export { buildScoringDomainModule } from "./scoring/dependencies/scoring-ddd.dependencies.js";

// Export all domain dependency types
export type { ClaimsDomainModule } from "./claims/dependencies/claims-ddd.dependencies.js";
export type { CompositionDomainModule } from "./composition/dependencies/composition-ddd.dependencies.js";
export type { EngagementDomainModule } from "./engagement/dependencies/engagement-ddd.dependencies.js";
export type { ExperienceDomainModule } from "./experience/dependencies/experience-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { PermittingDomainModule } from "./permitting/dependencies/permitting-ddd.dependencies.js";
export type { ReinsuranceDomainModule } from "./reinsurance/dependencies/reinsurance-ddd.dependencies.js";
export type { ScoringDomainModule } from "./scoring/dependencies/scoring-ddd.dependencies.js";
