/**
 * AutomaticSettlement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AutomaticSettlement DTOs
 *
 * DDD: Application DTOs for AutomaticSettlement use cases.
 */

import type { SettleClaimAutomaticallyRequestInput } from "@loadline/core/claims/types";

export type SettleClaimAutomaticallyInput = SettleClaimAutomaticallyRequestInput;

export type SettleClaimAutomaticallyOutput = {};
