/**
 * RecordFactorPermit handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { recordFactorPermit } from "@loadline/api-server/domains/permitting/handlers";
import type { PermittingDDDDependencies } from "@loadline/api-server/domains/permitting";
import { createFactorPermit as createFactorPermitEntity } from "@loadline/factories/permitting";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { PERMITTING_USE_CASES } from "../__factories__/use-cases.js";

describe("RecordFactorPermit", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PermittingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PermittingDDDDependencies>(
      PERMITTING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createFactorPermitEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRecordFactorPermit, "execute").mockResolvedValue(useCaseResult);

    await recordFactorPermit(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRecordFactorPermit.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
