/**
 * ExecuteListFactorPermits - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFactorPermits Use Case
 *
 * DDD: Application use case for list FactorPermit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFactorPermitsInput, ListFactorPermitsOutput } from "../dto/factor-permit.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@loadline/services/_shared/index.js";
import type { FactorPermitRepository } from "../ports/index.js";

export class ExecuteListFactorPermits {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly factorPermit: FactorPermitRepository
  ) {}

  async execute(input: ListFactorPermitsInput): Promise<ListFactorPermitsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prmId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.factorPermit.listFactorPermits({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFactorPermitsOutput;
  }
}
