/**
 * RaiseFraudReferral handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { raiseFraudReferral } from "@loadline/api-server/domains/claims/handlers";
import type { ClaimsDDDDependencies } from "@loadline/api-server/domains/claims";
import { createFraudReferral as createFraudReferralEntity } from "@loadline/factories/claims";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { CLAIMS_USE_CASES } from "../__factories__/use-cases.js";

describe("RaiseFraudReferral", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ClaimsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ClaimsDDDDependencies>(
      CLAIMS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createFraudReferralEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRaiseFraudReferral, "execute").mockResolvedValue(useCaseResult);

    await raiseFraudReferral(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRaiseFraudReferral.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
