/**
 * SavingsCredit Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SavingsCreditEntity } from "@loadline/core/experience/models/index.js";
import { experienceSchemas } from "@loadline/core/experience";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "exp";

export function createSavingsCredit(overrides: Partial<SavingsCreditEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    cohortId: overrides.cohortId ?? faker.string.uuid(),
    premiumTerm: overrides.premiumTerm ?? "expected_claims",
    status: overrides.status ?? "credited",
    ...overrides,
  };

  return experienceSchemas.SavingsCredit.parse(raw);
}

export function savingsCreditBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSavingsCredit(overrides));
}
