/**
 * ApiKey Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ApiKeyEntity } from "@loadline/core/identity/models/index.js";
import { identitySchemas } from "@loadline/core/identity";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "idn";

export function createApiKey(overrides: Partial<ApiKeyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    keyId: overrides.keyId ?? `key_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "active",
    ...overrides,
  };

  return identitySchemas.ApiKey.parse(raw);
}

export function apiKeyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createApiKey(overrides));
}
