/**
 * GetExpenseMeasurement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetExpenseMeasurementParams } from "@loadline/core/claims";

export function createGetExpenseMeasurementRequest(overrides: Partial<GetExpenseMeasurementParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
