/**
 * Disable DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disable DTOs
 *
 * DDD: Application DTOs for Disable use cases.
 */

import type { DisableTenantUserParams } from "@loadline/core/identity/types";

export type DisableTenantUserInput = DisableTenantUserParams;

export type DisableTenantUserOutput = {};
