/**
 * Logout DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Logout DTOs
 *
 * DDD: Application DTOs for Logout use cases.
 */

export type OperatorLogoutInput = {};

export type OperatorLogoutOutput = {};
