/**
 * Me DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Me DTOs
 *
 * DDD: Application DTOs for Me use cases.
 */

import type { UpdateOperatorMeRequestInput } from "@loadline/core/identity/types";

export type GetOperatorMeInput = {};

export type UpdateOperatorMeInput = UpdateOperatorMeRequestInput;

export type GetOperatorMeOutput = {};

export type UpdateOperatorMeOutput = {};
