/**
 * User DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * User DTOs
 *
 * DDD: Application DTOs for User use cases.
 */

import type { CreateTenantUserRequestInput, GetTenantUserParams, UpdateTenantUserParams, UpdateTenantUserRequestInput } from "@loadline/core/identity/types";

export type ListTenantUsersInput = {};

export type CreateTenantUserInput = CreateTenantUserRequestInput;

export type GetTenantUserInput = GetTenantUserParams;

export type UpdateTenantUserInput = UpdateTenantUserParams & UpdateTenantUserRequestInput;

export type ListTenantUsersOutput = {};

export type CreateTenantUserOutput = {};

export type GetTenantUserOutput = {};

export type UpdateTenantUserOutput = {};
