/**
 * ApiKeyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApiKeyRepository Port
 *
 * DDD: Application port for apikeyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTenantApiKeyInput, CreateTenantApiKeyOutput, GetTenantApiKeyInput, GetTenantApiKeyOutput, ListTenantApiKeysInput, ListTenantApiKeysOutput, RevokeTenantApiKeyInput, RevokeTenantApiKeyOutput } from "../dto/api-key.dto.js";
export interface ApiKeyRepository {
  listTenantApiKeys(input: ListTenantApiKeysInput): Promise<ListTenantApiKeysOutput>;
  createTenantApiKey(input: CreateTenantApiKeyInput): Promise<CreateTenantApiKeyOutput>;
  getTenantApiKey(input: GetTenantApiKeyInput): Promise<GetTenantApiKeyOutput>;
  revokeTenantApiKey(input: RevokeTenantApiKeyInput): Promise<RevokeTenantApiKeyOutput>;
}

export type { CreateTenantApiKeyInput, CreateTenantApiKeyOutput, GetTenantApiKeyInput, GetTenantApiKeyOutput, ListTenantApiKeysInput, ListTenantApiKeysOutput, RevokeTenantApiKeyInput, RevokeTenantApiKeyOutput } from "../dto/api-key.dto.js";
