/**
 * EnableRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EnableRepository Port
 *
 * DDD: Application port for enablerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { EnableTenantUserInput, EnableTenantUserOutput } from "../dto/enable.dto.js";
export interface EnableRepository {
  enableTenantUser(input: EnableTenantUserInput): Promise<EnableTenantUserOutput>;
}

export type { EnableTenantUserInput, EnableTenantUserOutput } from "../dto/enable.dto.js";
