/**
 * MeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MeRepository Port
 *
 * DDD: Application port for merepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetOperatorMeInput, GetOperatorMeOutput, UpdateOperatorMeInput, UpdateOperatorMeOutput } from "../dto/me.dto.js";
export interface MeRepository {
  getOperatorMe(input: GetOperatorMeInput): Promise<GetOperatorMeOutput>;
  updateOperatorMe(input: UpdateOperatorMeInput): Promise<UpdateOperatorMeOutput>;
}

export type { GetOperatorMeInput, GetOperatorMeOutput, UpdateOperatorMeInput, UpdateOperatorMeOutput } from "../dto/me.dto.js";
