/**
 * RefreshRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RefreshRepository Port
 *
 * DDD: Application port for refreshrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { OperatorRefreshInput, OperatorRefreshOutput } from "../dto/refresh.dto.js";
export interface RefreshRepository {
  operatorRefresh(input: OperatorRefreshInput): Promise<OperatorRefreshOutput>;
}

export type { OperatorRefreshInput, OperatorRefreshOutput } from "../dto/refresh.dto.js";
