/**
 * UserRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UserRepository Port
 *
 * DDD: Application port for userrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTenantUserInput, CreateTenantUserOutput, GetTenantUserInput, GetTenantUserOutput, ListTenantUsersInput, ListTenantUsersOutput, UpdateTenantUserInput, UpdateTenantUserOutput } from "../dto/user.dto.js";
export interface UserRepository {
  listTenantUsers(input: ListTenantUsersInput): Promise<ListTenantUsersOutput>;
  createTenantUser(input: CreateTenantUserInput): Promise<CreateTenantUserOutput>;
  getTenantUser(input: GetTenantUserInput): Promise<GetTenantUserOutput>;
  updateTenantUser(input: UpdateTenantUserInput): Promise<UpdateTenantUserOutput>;
}

export type { CreateTenantUserInput, CreateTenantUserOutput, GetTenantUserInput, GetTenantUserOutput, ListTenantUsersInput, ListTenantUsersOutput, UpdateTenantUserInput, UpdateTenantUserOutput } from "../dto/user.dto.js";
