/**
 * Routes for Consent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { recordConsentChange, resolveConsentState } from "../handlers/consent.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function consentRoutes(fastify: FastifyInstance) {
  // POST /v1/risk-subjects/{riskSubjectId}/consent (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/risk-subjects/:riskSubjectId/consent",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { riskSubjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getScoringDependenciesForRequest();
        await recordConsentChange(request, reply, deps);
      });
    }
  );


  // GET /v1/risk-subjects/{riskSubjectId}/consent (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/risk-subjects/:riskSubjectId/consent",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { riskSubjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getScoringDependenciesForRequest();
        await resolveConsentState(request, reply, deps);
      });
    }
  );


}
