/**
 * Routes for Explanation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getScoreExplanation } from "../handlers/explanation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function explanationRoutes(fastify: FastifyInstance) {
  // GET /v1/scores/{scoreId}/explanation (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/scores/:scoreId/explanation",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { scoreId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getScoringDependenciesForRequest();
        await getScoreExplanation(request, reply, deps);
      });
    }
  );


}
