/**
 * Composition DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Composition Domain Module - Composition root
 *
 * DDD: Composition root for composition domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CalibrationRepositoryAdapter,
  CompositionRepositoryAdapter,
  OfferRepositoryAdapter,
  VariationEnvelopeRepositoryAdapter,
} from "@loadline/adapters/composition";
import { getIdGeneratorService } from "@loadline/adapters";
import type { AdapterDynamoDBClient } from "@loadline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApplyCommercialCalibration,
  ExecuteComposePremium,
  ExecuteIssuePriceOffer,
  ExecuteListVariationEnvelopes,
  ExecuteSetVariationEnvelope,
} from "@loadline/services/composition/usecases";
// Ports (interfaces)
import type {
  CalibrationRepository,
  CompositionRepository,
  OfferRepository,
  VariationEnvelopeRepository,
} from "@loadline/services/composition/ports";

export interface CompositionDomainModule {
  repos: {
    calibrations: CalibrationRepository;
    compositions: CompositionRepository;
    offers: OfferRepository;
    variationEnvelopes: VariationEnvelopeRepository;
  };
  useCases: {
    calibrations: {
      get: ExecuteApplyCommercialCalibration;
    };
    compositions: {
      get: ExecuteComposePremium;
    };
    offers: {
      get: ExecuteIssuePriceOffer;
    };
    variationEnvelopes: {
      list: ExecuteListVariationEnvelopes;
      update: ExecuteSetVariationEnvelope;
    };
  };
}

export function buildCompositionDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CompositionDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      calibrations?: CalibrationRepository;
      compositions?: CompositionRepository;
      offers?: OfferRepository;
      variationEnvelopes?: VariationEnvelopeRepository;
    } = {};

    obj.calibrations = new CalibrationRepositoryAdapter(dynamoClient);
    obj.compositions = new CompositionRepositoryAdapter(dynamoClient);
    obj.offers = new OfferRepositoryAdapter(dynamoClient);
    obj.variationEnvelopes = new VariationEnvelopeRepositoryAdapter(dynamoClient);
    return {
      calibrations: obj.calibrations!,
      compositions: obj.compositions!,
      offers: obj.offers!,
      variationEnvelopes: obj.variationEnvelopes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    calibrations: {
      get: new ExecuteApplyCommercialCalibration(executionContext, idGenerator, repos.calibrations),
    },
    compositions: {
      get: new ExecuteComposePremium(executionContext, idGenerator, repos.compositions),
    },
    offers: {
      get: new ExecuteIssuePriceOffer(executionContext, idGenerator, repos.offers),
    },
    variationEnvelopes: {
      list: new ExecuteListVariationEnvelopes(executionContext, idGenerator, repos.variationEnvelopes),
      update: new ExecuteSetVariationEnvelope(executionContext, idGenerator, repos.variationEnvelopes),
    },
  };
  return { repos, useCases: useCases as CompositionDomainModule["useCases"] };
}
