/**
 * Observation Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ObservationEntity } from "@loadline/core/experience/models/index.js";
import { experienceSchemas } from "@loadline/core/experience";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "exp";

export function createObservation(overrides: Partial<ObservationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    cohortId: overrides.cohortId ?? faker.string.uuid(),
    period: overrides.period ?? faker.lorem.word(),
    ...overrides,
  };

  return experienceSchemas.ExperienceObservation.parse(raw);
}

export function observationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createObservation(overrides));
}
