/**
 * ExpenseMeasurementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExpenseMeasurementRepository Port
 *
 * DDD: Application port for expensemeasurementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetExpenseMeasurementInput, GetExpenseMeasurementOutput } from "../dto/expense-measurement.dto.js";
export interface ExpenseMeasurementRepository {
  getExpenseMeasurement(input: GetExpenseMeasurementInput): Promise<GetExpenseMeasurementOutput>;
}

export type { GetExpenseMeasurementInput, GetExpenseMeasurementOutput } from "../dto/expense-measurement.dto.js";
