/**
 * FraudReferralRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FraudReferralRepository Port
 *
 * DDD: Application port for fraudreferralrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RaiseFraudReferralInput, RaiseFraudReferralOutput } from "../dto/fraud-referral.dto.js";
export interface FraudReferralRepository {
  raiseFraudReferral(input: RaiseFraudReferralInput): Promise<RaiseFraudReferralOutput>;
}

export type { RaiseFraudReferralInput, RaiseFraudReferralOutput } from "../dto/fraud-referral.dto.js";
