/**
 * ListVariationEnvelope DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListVariationEnvelopesParams } from "@loadline/core/composition";

export function createListVariationEnvelopeRequest(overrides: Partial<ListVariationEnvelopesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
