/**
 * Scoring DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scoring Domain Module - Composition root
 *
 * DDD: Composition root for scoring domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ConsentRepositoryAdapter,
  ExplanationRepositoryAdapter,
  ScoreRepositoryAdapter,
} from "@loadline/adapters/scoring";
import { getIdGeneratorService } from "@loadline/adapters";
import type { AdapterDynamoDBClient } from "@loadline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetScoreExplanation,
  ExecuteRecordConsentChange,
  ExecuteResolveConsentState,
  ExecuteScoreRiskSubject,
} from "@loadline/services/scoring/usecases";
// Ports (interfaces)
import type {
  ConsentRepository,
  ExplanationRepository,
  ScoreRepository,
} from "@loadline/services/scoring/ports";

export interface ScoringDomainModule {
  repos: {
    consents: ConsentRepository;
    explanations: ExplanationRepository;
    scores: ScoreRepository;
  };
  useCases: {
    consents: {
      get: ExecuteRecordConsentChange;
    };
    explanations: {
      get: ExecuteGetScoreExplanation;
    };
    scores: {
      get: ExecuteScoreRiskSubject;
    };
  };
}

export function buildScoringDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ScoringDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      consents?: ConsentRepository;
      explanations?: ExplanationRepository;
      scores?: ScoreRepository;
    } = {};

    obj.consents = new ConsentRepositoryAdapter(dynamoClient);
    obj.explanations = new ExplanationRepositoryAdapter(dynamoClient);
    obj.scores = new ScoreRepositoryAdapter(dynamoClient);
    return {
      consents: obj.consents!,
      explanations: obj.explanations!,
      scores: obj.scores!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    consents: {
      get: new ExecuteRecordConsentChange(executionContext, idGenerator, repos.consents),
    },
    explanations: {
      get: new ExecuteGetScoreExplanation(executionContext, idGenerator, repos.explanations),
    },
    scores: {
      get: new ExecuteScoreRiskSubject(executionContext, idGenerator, repos.scores),
    },
  };
  return { repos, useCases: useCases as ScoringDomainModule["useCases"] };
}
