/**
 * DeleteApiKey DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RevokeTenantApiKeyParams } from "@loadline/core/identity";

export function createDeleteApiKeyRequest(overrides: Partial<RevokeTenantApiKeyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
