/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the experience domain.
 * Use these factories in tests to create test data.
 */

export { createCohort } from "./cohort/entity/cohort.entity.factory.js";
export { createObservation } from "./observation/entity/observation.entity.factory.js";
export { createSavingsCredit } from "./savings-credit/entity/savings-credit.entity.factory.js";
