/**
 * ListObservation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListExperienceObservationsParams } from "@loadline/core/experience";

export function createListObservationRequest(overrides: Partial<ListExperienceObservationsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
