/**
 * Routes for AutomaticSettlement
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { settleClaimAutomatically } from "../handlers/automatic-settlement.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function automaticSettlementRoutes(fastify: FastifyInstance) {
  // POST /v1/claims/automatic-settlements (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/claims/automatic-settlements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getClaimsDependenciesForRequest();
        await settleClaimAutomatically(request, reply, deps);
      });
    }
  );


}
