/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { automaticSettlementRoutes } from "./automatic-settlement.routes.js";
export { expenseMeasurementRoutes } from "./expense-measurement.routes.js";
export { fraudReferralRoutes } from "./fraud-referral.routes.js";
