/**
 * Repository interface for Programme
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProgrammeEntity
} from "../models/programme.entity.js";
import type {
  ListEngagementProgrammesParams,
  EngagementProgramme
} from "../types/index.js";
/**
 * ProgrammeRepository Interface
 */
export interface ProgrammeRepository extends CreateReadRepository<ProgrammeEntity, EngagementProgramme, string, ListEngagementProgrammesParams> {

}
