/**
 * Repository interface for Touchpoint
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TouchpointEntity
} from "../models/touchpoint.entity.js";
import type {
  TouchpointEvent
} from "../types/index.js";
/**
 * TouchpointRepository Interface
 */
export interface TouchpointRepository extends CreateReadRepository<TouchpointEntity, TouchpointEvent, string, Record<string, never>> {

}
