/**
 * Cohort Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/experience.openapi.types.js";
import { schemas } from "../schemas/experience.schemas.js";

/**
 * Entity: CohortEntity
 * Description: Represents the Cohort domain model.
 * Source: schemas.CohortDefinition
 * Type: Persisted Entity (x-dynamodb)
 */
export const CohortEntitySchema = schemas.CohortDefinition;
export type CohortEntity = components["schemas"]["CohortDefinition"];
