/**
 * Observation Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/experience.openapi.types.js";
import { schemas } from "../schemas/experience.schemas.js";

/**
 * Entity: ObservationEntity
 * Description: Represents the Observation domain model.
 * Source: schemas.ExperienceObservation
 * Type: Persisted Entity (x-dynamodb)
 */
export const ObservationEntitySchema = schemas.ExperienceObservation;
export type ObservationEntity = components["schemas"]["ExperienceObservation"];
