/**
 * Test utilities barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Scoring Service Test Utilities
 *
 * Barrel export for factories, mock repositories, and test helpers.
 * Import these in scoring service tests for consistent mocking.
 */

// Factories (entity and DTO factories) - use barrel export
export * from "./factories/index.js";

// Mock repositories are not needed - use createMockDependencies from @loadline/tests/shared
// export * from "./mocks/index.js";

// Test setup helpers (now in shared, but keeping for backward compatibility)
export {
  TEST_JWT_SECRET,
  TEST_ORG_ID,
  TEST_ACCOUNT_ID,
  TEST_USER_EMAIL,
  generateAuthToken,
  parseJsonResponse,
} from "@loadline/tests/shared";
