/**
 * CohortRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CohortRepository Port
 *
 * DDD: Application port for cohortrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DefineCohortInput, DefineCohortOutput, ListCohortDefinitionsInput, ListCohortDefinitionsOutput } from "../dto/cohort.dto.js";
export interface CohortRepository {
  listCohortDefinitions(input: ListCohortDefinitionsInput): Promise<ListCohortDefinitionsOutput>;
  defineCohort(input: DefineCohortInput): Promise<DefineCohortOutput>;
}

export type { DefineCohortInput, DefineCohortOutput, ListCohortDefinitionsInput, ListCohortDefinitionsOutput } from "../dto/cohort.dto.js";
