/**
 * Review Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/reinsurance.openapi.types.js";
import { schemas } from "../schemas/reinsurance.schemas.js";

/**
 * Entity: ReviewEntity
 * Description: Represents the Review domain model.
 * Source: schemas.ReviewDecision
 * Type: Persisted Entity (x-dynamodb)
 */
export const ReviewEntitySchema = schemas.ReviewDecision;
export type ReviewEntity = components["schemas"]["ReviewDecision"];
