/**
 * Handlers for Refresh
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IdentityDomainModule } from "../dependencies/identity-ddd.dependencies.js";
import type { OperatorRefreshInput } from "@loadline/services/identity";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/auth/refresh
 * Operation: operatorRefresh
 */
export async function operatorRefresh(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: IdentityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OperatorRefreshInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.refreshes.get.execute(input);
  return reply.code(200).send(result);
}


