/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the identity domain.
 * Use these factories in tests to create test data.
 */

export { createApiKey } from "./api-key/entity/api-key.entity.factory.js";
export { createUpdateDisableRequest } from "./disable/dto/update-disable.dto.factory.js";
export { createUpdateEnableRequest } from "./enable/dto/update-enable.dto.factory.js";
