/**
 * Composition Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CompositionEntity } from "@loadline/core/composition/models/index.js";
import { compositionSchemas } from "@loadline/core/composition";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cmp";

export function createComposition(overrides: Partial<CompositionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    riskSubjectId: overrides.riskSubjectId ?? faker.string.uuid(),
    technicalCost: overrides.technicalCost ?? {
      amount: 0,
      currency: ""
    },
    ...overrides,
  };

  return compositionSchemas.PremiumComposition.parse(raw);
}

export function compositionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createComposition(overrides));
}
