/**
 * Claims DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: claims
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Claims Domain Module - Composition root
 *
 * DDD: Composition root for claims domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AutomaticSettlementRepositoryAdapter,
  ExpenseMeasurementRepositoryAdapter,
  FraudReferralRepositoryAdapter,
} from "@loadline/adapters/claims";
import { getIdGeneratorService } from "@loadline/adapters";
import type { AdapterDynamoDBClient } from "@loadline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetExpenseMeasurement,
  ExecuteRaiseFraudReferral,
  ExecuteSettleClaimAutomatically,
} from "@loadline/services/claims/usecases";
// Ports (interfaces)
import type {
  AutomaticSettlementRepository,
  ExpenseMeasurementRepository,
  FraudReferralRepository,
} from "@loadline/services/claims/ports";

export interface ClaimsDomainModule {
  repos: {
    automaticSettlements: AutomaticSettlementRepository;
    expenseMeasurements: ExpenseMeasurementRepository;
    fraudReferrals: FraudReferralRepository;
  };
  useCases: {
    automaticSettlements: {
      update: ExecuteSettleClaimAutomatically;
    };
    expenseMeasurements: {
      get: ExecuteGetExpenseMeasurement;
    };
    fraudReferrals: {
      get: ExecuteRaiseFraudReferral;
    };
  };
}

export function buildClaimsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ClaimsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      automaticSettlements?: AutomaticSettlementRepository;
      expenseMeasurements?: ExpenseMeasurementRepository;
      fraudReferrals?: FraudReferralRepository;
    } = {};

    obj.automaticSettlements = new AutomaticSettlementRepositoryAdapter(dynamoClient);
    obj.expenseMeasurements = new ExpenseMeasurementRepositoryAdapter(dynamoClient);
    obj.fraudReferrals = new FraudReferralRepositoryAdapter(dynamoClient);
    return {
      automaticSettlements: obj.automaticSettlements!,
      expenseMeasurements: obj.expenseMeasurements!,
      fraudReferrals: obj.fraudReferrals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    automaticSettlements: {
      update: new ExecuteSettleClaimAutomatically(executionContext, idGenerator, repos.automaticSettlements),
    },
    expenseMeasurements: {
      get: new ExecuteGetExpenseMeasurement(executionContext, idGenerator, repos.expenseMeasurements),
    },
    fraudReferrals: {
      get: new ExecuteRaiseFraudReferral(executionContext, idGenerator, repos.fraudReferrals),
    },
  };
  return { repos, useCases: useCases as ClaimsDomainModule["useCases"] };
}
