/**
 * ListCohortDefinitions handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listCohortDefinitions } from "@loadline/api-server/domains/experience/handlers";
import type { ExperienceDDDDependencies } from "@loadline/api-server/domains/experience";
import { createCohort as createCohortEntity } from "@loadline/factories/experience";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { EXPERIENCE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListCohortDefinitions", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ExperienceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ExperienceDDDDependencies>(
      EXPERIENCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createCohortEntity({ orgId }),
      createCohortEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListCohortDefinitions, "execute").mockResolvedValue(useCaseResult);

    await listCohortDefinitions(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListCohortDefinitions.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
