/**
 * Review Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ReviewEntity } from "@loadline/core/reinsurance/models/index.js";
import { reinsuranceSchemas } from "@loadline/core/reinsurance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rei";

export function createReview(overrides: Partial<ReviewEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    decisionId: overrides.decisionId ?? faker.string.uuid(),
    status: overrides.status ?? "open",
    ...overrides,
  };

  return reinsuranceSchemas.ReviewDecision.parse(raw);
}

export function reviewBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createReview(overrides));
}
