/**
 * Routes for SavingsCredit
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: experience
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { creditExpectedClaimsSaving } from "../handlers/savings-credit.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function savingsCreditRoutes(fastify: FastifyInstance) {
  // POST /v1/experience/savings-credits (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/experience/savings-credits",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExperienceDependenciesForRequest();
        await creditExpectedClaimsSaving(request, reply, deps);
      });
    }
  );


}
