/**
 * Routes for PermittingModel
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listRiskModels, submitRiskModel } from "../handlers/permitting-model.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function permittingModelRoutes(fastify: FastifyInstance) {
  // GET /v1/permitting/models (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/permitting/models",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPermittingDependenciesForRequest();
        await listRiskModels(request, reply, deps);
      });
    }
  );


  // POST /v1/permitting/models (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/permitting/models",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPermittingDependenciesForRequest();
        await submitRiskModel(request, reply, deps);
      });
    }
  );


}
