/**
 * GetFrequency DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: engagement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetTouchpointFrequencyParams } from "@loadline/core/engagement";

export function createGetFrequencyRequest(overrides: Partial<GetTouchpointFrequencyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
