/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Reinsurance Domain Use Cases
 * 
 * List of all use case names for the reinsurance domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const REINSURANCE_USE_CASES = [
  "executeGetCessionExperience",
  "executeRequestHumanReview"
] as const;
