/**
 * DisableTenantUser handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { disableTenantUser } from "@loadline/api-server/domains/identity/handlers";
import type { IdentityDDDDependencies } from "@loadline/api-server/domains/identity";
import { createUpdateDisableRequest } from "@loadline/factories/identity";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@loadline/tests/shared";
import { IDENTITY_USE_CASES } from "../__factories__/use-cases.js";

describe("DisableTenantUser", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IdentityDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IdentityDDDDependencies>(
      IDENTITY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = createUpdateDisableRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { userId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDisableTenantUser, "execute").mockResolvedValue(useCaseResult);

    await disableTenantUser(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDisableTenantUser.execute).toHaveBeenCalledWith(expect.objectContaining({ userId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
