/**
 * FactorPermitRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FactorPermitRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FactorPermitRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FactorPermitRepository,
} from "@loadline/services/permitting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FactorPermitRepositoryDdb } from "./factor-permit-repository.ddb.js";

/**
 * FactorPermitRepositoryAdapter
 *
 * Implements FactorPermitRepository port for infrastructure layer.
 */
export class FactorPermitRepositoryAdapter implements FactorPermitRepository {
  private readonly ddb: FactorPermitRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FactorPermitRepositoryDdb(this.dynamoClient);
  }

  async listFactorPermits(input: Parameters<FactorPermitRepository['listFactorPermits']>[0]): Promise<Awaited<ReturnType<FactorPermitRepository['listFactorPermits']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFactorPermits(input);
  }

  async recordFactorPermit(input: Parameters<FactorPermitRepository['recordFactorPermit']>[0]): Promise<Awaited<ReturnType<FactorPermitRepository['recordFactorPermit']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordFactorPermit(input);
  }
}
