/**
 * ValidationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValidationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ValidationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ValidationRepository,
} from "@loadline/services/permitting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ValidationRepositoryDdb } from "./validation-repository.ddb.js";

/**
 * ValidationRepositoryAdapter
 *
 * Implements ValidationRepository port for infrastructure layer.
 */
export class ValidationRepositoryAdapter implements ValidationRepository {
  private readonly ddb: ValidationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ValidationRepositoryDdb(this.dynamoClient);
  }

  async validateRiskModel(input: Parameters<ValidationRepository['validateRiskModel']>[0]): Promise<Awaited<ReturnType<ValidationRepository['validateRiskModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.validateRiskModel(input);
  }
}
