/**
 * ValidationQueueRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: permitting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValidationQueueRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ValidationQueueRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ValidationQueueRepository,
} from "@loadline/services/permitting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ValidationQueueRepositoryDdb } from "./validation-queue-repository.ddb.js";

/**
 * ValidationQueueRepositoryAdapter
 *
 * Implements ValidationQueueRepository port for infrastructure layer.
 */
export class ValidationQueueRepositoryAdapter implements ValidationQueueRepository {
  private readonly ddb: ValidationQueueRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ValidationQueueRepositoryDdb(this.dynamoClient);
  }

  async getValidationQueue(input: Parameters<ValidationQueueRepository['getValidationQueue']>[0]): Promise<Awaited<ReturnType<ValidationQueueRepository['getValidationQueue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getValidationQueue(input);
  }
}
