/**
 * CessionExperience DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reinsurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CessionExperience DTOs
 *
 * DDD: Application DTOs for CessionExperience use cases.
 */

import type { GetCessionExperienceParams } from "@loadline/core/reinsurance/types";

export type GetCessionExperienceInput = GetCessionExperienceParams;

export type GetCessionExperienceOutput = {};
