/**
 * Offer Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: composition
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/composition.openapi.types.js";
import { schemas } from "../schemas/composition.schemas.js";

/**
 * Entity: OfferEntity
 * Description: Represents the Offer domain model.
 * Source: schemas.PriceOffer
 * Type: Persisted Entity (x-dynamodb)
 */
export const OfferEntitySchema = schemas.PriceOffer;
export type OfferEntity = components["schemas"]["PriceOffer"];
